<?php //006ed
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Kundenmanager @version 4.1.2.3 PHP71 (10.05.2021) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2021, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cP/3EOKHa4LfiSNtqP+2rS7NDdcIG32Re3Pku4QHY3tMkaFqJo/f1jzGSlma5MnLhqFQZiSZZ
C7azxV7Sy+k2R40A8mjhEi8urzZJhYb/564ipalVfzb5HjWRKSLvMKRiyx1/AeoZzs8NmwT9lPb1
ULbMTSMcMX9tv6uzwrp8W+LqvYJfMLajbzdT1lwuj/F07Fvim63Qyq7aE/+iOyV4N1wJ6iTXiQtG
6qeQI8KKaoj3OszLJIQmwiJ6GTtoY0mkb4/LDKXZ9p8BkvhFAdGnwbsQmQHhdCstY1ydUEbowZZS
mQH7/uX6RAmXOoGjpHJcZ6abMp1m9GmMZxETTty/Zzr+2bu3Sz7xXCw7kQb0azktwGzirnKFjGal
IA6quWewCyjhCUwtcgTB3m5234oELMjSimlBcKTVUtEUAJU7tx3F8YCV8q5Zcj/3K9Dr4hDo/wL2
CEtc/IlDkMkD5YZKLFFlqJ+kVDry1bmeRlA8Ho9qiClDqGSvM5sY5akZnH0tqnSVLagMKxh0/ug+
DCmsvoQbU7UpVYzeDp2hTTQbZ2NHknlWAJulO4LROEUmlxuQone76yxTYfQzyR/cXuh3MWqcJ+9/
fJwZBO1P9AgmoC2Gj2WgQn+E68kFavM5NvdExB6Yj5J/HM0LnNZT77RLLyxwyZX43xH/Po6+ZXQg
mtRzYiW78VRd+M0Blojw2SxPFxtypDj9jX2aTsJNZOPHZjjuKVc1WaVJumqwf/Kh7VmYZyE8zIOR
+/Oum9/3FVzER/+WL2+LsiYohxDgZPWhXGjwgmiUC05SsNuumglhadgtM5EZex659sfH2oOGxl05
Ry7uZdXGM+eOi9dgd4npLccS1rjTg3dEp/U7uWB0tSu0TzHGhUBnWRgn5Vwm3xquDXXfl8tdwdr8
0XVRfW78+FPQX5SVRkL7z5oiXleGc6pesyhRnUSfnBh6IWcHiYNegi43cnlt0Ka290VfBw/bRVTh
08Ee8NkUkLtmSp2YsTcGYGl6KivApLorblfRsH2fJVCviLZhsu+vq2tyxiVnuvPBCuvflSvsVUQm
UxBuHhTejC/8ewqNP55BeAcFFf6ltoVS0XvBrawX0w8M2OxRuJ+qglaLD+GjxQkK2I3NJfAYfts8
hFtw1pv9rCYaDDFeo+Q1/dA3sa4sZsI2Oo38b1dO1v4MY1nCYSRCi35o1r53smgeDrbvAfdP0OXJ
y93no94AxvAiOepGuE7gWsEqB0mLk4kUHyLKUsXdolrTES4U4QgnSVnJxLYvOYgsnBvwQXx6vAll
4KP3AFBt3avfJ2YsWm7Qaw1Xbr/N1MDRDboRLWkFVYvLdrfsFl50NWSUM4mkH1etAseWE7z+tdka
gbvhEIp8lB+nW4TyUx4SigG9fa80ePpvukfgr7ro5HsF08HbQ9jHOhsCbeCOm6cxlTCV9ToybRyd
ZP8nU430ehsyRWz1g9LpsYnx1D+T9LnqpKvIrTOLVZ/v1mOXBhN8qG7qFb8O18QoajDLZwf4eMy9
Dvepqr+b9xlZgMOGUkKZlFZOPen5mCV2ZjcryMVPLKnlAFwoMO6uq59LSNfnRNPJJJEeDy3PWFn2
lCgVhnN5nx1AtZAFKjfQxDX/jv/DrglA8im3itC9lC6Oh2dyrl2JkFjqnaBr1BMZQj7kV1wwZ9ht
cDoP/P1tK5M9nMh/HSS2njeXPXwS/c4lcSt5jltxkOw/84VzjUU77pVzCWmkxmQTkCcQ5t0H0C9I
b54jcE7z8QdNUOUArAPul7/UUi0CFxH0cnLjTxzi3Oev8SPpDjwBK4Kgf6Q1ejh8rWkSLm89hog4
qjMOs8+8y3s7WSYCRKXmNsNEvPXcL5NYEwjCvn4eJffOKHR9om196pOtUxGYjnC3LzpHYfFJf0ir
oou8J4cC/okdSz/cpGOApNIbL2RqvLXsr8xrY5zTmXIRgbZupHLthNMDqM1ksI40DyEmOGWsi7I+
opxiLHz3ql6erKH8JQEsgUodNDDf8l0bfL+RO+4VKFHz9fwrBKRJA2g8X/a+efbST0JUB+KQT3tt
kDVCfkPUS24DkTLipfr2hxPVMULtoOaj4/g8SbFKQ4xpTVR8xsUFTtAJWdFaRR1RHiu4fGbR806f
GHDExYDLp4LWux9ZbzLT3Ts5UYq+VIk3bOzAaDA3k/tcgqFlIL8z+/yOswUYU1BfkaZkdTRnBmlU
6kH5GrAWggkpTm0ZjyCSBk7hrQMTosZO2cU4aUl6H2qeXwCNjT3TsYIM4H3ALeaCx0ga+LByKL6s
kXluYUGNQtNPXKjAXxclU/BTkkJTU2cje1SJHCYA3gqId/jeYql0GluzfCdYadMfKQAqqscAVi29
sfB3I7uJ2NW1cxZgVDiaHHmGAVierD+FxYIdMDDAsmWG32J4A9hBWv33c+Vs5qafPIrOPxmoMYdK
wzZ9Zm7ugROCbIrPunXJrKcG3qVqEzTamyFE6eJkB2YJRDXdqxu24Ql2J2VcAkFwaCzLmujou3dU
CluoiujLoke1JEdAiv1HZBSoa6DXxCS4u/BzKdJ9h7TBVZh8B1W3XavzGhxM31NcM7GUyboWffi/
wV29ZQxcnOr9l5tzdsGw4cfH9j/wS5mQoXogLiHOVqdeELqw+oc2O7yiMW4WiflmW7ten+IjiPna
ooxQVcThWIMCPfXt3PrHdJrUmOpdtXs/U3qSrB1yaIbNpMy7aQWHyJ++BQXr2gM8pru2MJsUyrb4
uAVvAXWEEpNf2NUpRY2BfGXt/hFfj3DSt2XpXQDx0kGGjNeiKiali4LA2h9pKnPY39a52gS4u5Hj
jRzWV9o+RjxPKociIhxteW==