<?php //006f9
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Kundenmanager @version 5.1.1.3 PHP73 (03.05.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPzfq6xmFqly+izR0Zf/To79w+l/4R7oT2BIuCpNy8MKEFWPszEe7fjENSzG32Y3ah9eYcdqP
YnOUqSy6eCNCr4l8BM6ArIsUpi4iNtK0s1pgCFxLgdEkbBQJLAlIygM8d6zs9IIuPWFpzf9/Tq42
auMCejFsivTmaplDUDTWErqg6KWNl749ORzFIk3Tm5l8Qa2N+GbuJgbxXNsnFQJsqvWbpG3oYQLX
eHoM4jJFs7jexdISY/3HnKtLWMxXanE+bPfPR0Vf1kk2KfvYPTXIkqyb3P5jV8rS6QbxM3qQpvd4
0PmMnydISZuLpoe9+VkkutZOC8hP5yUIXJbYgfMTSITNfnkOrzPEnm8pYKzy1uu5Tl3hC8E8XeCg
IGJhT64U7ozTqrEQUruxwbHDfxkglBx0ojMaz44+Cyo1erivjIrhZrVhCrLlOvTr+xjCij0Rcv8E
Psh+ianVvOn4WhITjD5JsoNGLcfp9dD+HMhFUBpR6T5Ctmj5Pil3QztpTQp5Jj8HQc7Da1533AxA
l3zt6N5NlUa4rHlIJgataaJLqGQPvS+z7bYvtbYS1+EtY6KIeW==