<?php //006f9
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Kundenmanager @version 5.1.1.1 PHP73 (16.03.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPo3CKJLPAgew97Z45g5HMQABQxsMdtVYsEKvLSwdfhSiTt9HNdpDksh+0MSBLYv0aQIUowfK
fIrNNKHtSeHeYNevnuiXMsxCxBwF+r1Qq8Le0hq8gduPAMo7G4MHUbWBwDTljYEVvnPYsCuTWTWC
KPthqisu5Uwp6MyF3zjWijIa8Q8O5sFmChKKHhEsBQGdYx6Em9+5BeBCntNHi9uLtOmIuQXvIUhq
sWYYXCqf9YSw0TH65DwGm3vlq95i8dCGMvh7vStZmQGOwyumWgSSDr+lPl0UQ79D1pO/upe7pibh
ImgxVvne9R04y34L5iVGm6V60mshSIV1I0UBbBfVway2vel/22gqhjK2JpJyP/o7PkrYmRelc/RO
USiwtbz95EsOrmherSMYTqqWVLbtElzNtoiMEF2s+axQdCOvZZhSJm1O9lZhxUZO1tTKRyYeiMu2
UivqwGqUobZRVFQhxCwTtCPD7By0ufCGa5Uh59z/uWvUjv8vgZ1ODKGkzixEO6gVd5y9R2nJ/fZ/
nuoIdxGP8KpYnPKhgfyia9rk7EVFpGK4YUb6I0kBrBWAxGo+LFwl+w8tQpzV