<?php //006f9
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Kundenmanager @version 5.1.3.0 PHP73 (07.09.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPx8M2VsW/F7olQAStZ5ycNDj1bgqLBjxtwIuWP2wlCdQVAoZjgKOA2VaU57nbeik0EXg64+l
MtZ9+cr50ZLtwL3iPnsfsjV3WCW5uRX76LAl+a6O/ma0yMmEC9e/rakn5ZBUof5oXc5MCmJOC2Jt
7wj/sZBVKbrjPbplmitXXBPaGfv5mDK74wmBLs2yz4sN1bfo5+XO+xkpBdgrjob4pKeqvXnC7vAB
bT8YUa0T1RyP41kypHdLMnBNce8ZerqsGSySl5pac3wYAsXqtbdIJctyCEndly66rhLpx1lxPRzw
yRi4nlAmCCjWGgUCJ6ndTf/abVVjDX2WK5bF9BtfSSEC1FpceIvIof9R+qpvGsKljxknmp6C2Rcg
YAdJ0Jiky5yFOMBL0CYVobSqqBiDNs80jsmw29he7gaWMLshRHniCaSZkU7a5i2OasmR/F0wFgnI
ytuj4fuuRDPxtQ7ho8zhpmq4Dw6Hjezv0COEStVLwPKx3r7JOanvmqjPfLWHZY5wghlf+ZzyTA1T
zmj+6k1R6R5/yoVGouN/L7BgTZX96HAz++qr3gwDVBMlOdti