<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * https://www.d3data.de
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      https://www.oxidmodule.com
 */

// @codeCoverageIgnoreStart

$sLangName = 'Deutsch';

// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                          => 'UTF-8',

    'd3mxusermanager'                                  => '<i class="fa fa-fw fa-users"></i> Kundenmanager',
    'd3mxusermanager_settings'                         => 'Einstellungen',
    'd3tbclusermanager_settings_main'                  => 'Grundeinstellungen',
    'd3mxusermanager_items'                            => 'Aufgaben',

    'd3tbclusermanager_items_main'                     => 'Stamm',
    'd3tbclusermanager_items_main_desc'                 => 'Hier finden Sie die Grundeinstellungen zu jeder Aufgabe. Vergeben Sie einen aussagekräftigen Titel, um die Aufgabe jederzeit wiederzuerkennen.',
    'd3tbclusermanager_items_mall'                     => 'Mall',
    'd3tbclusermanager_items_mall_desc'                 => 'Setzen Sie eine Shopinstallation mit mehreren Mandanten ein (z.B. Enterprise Edition), können Sie Aufgaben gleichzeitig für verschiedene Mandanten zuweisen. Eine erneute Anlage ist nicht nötig.',
    'd3tbclusermanager_items_trigger'                   => 'Auslöser',
    'd3tbclusermanager_items_trigger_desc'              => 'Mit den Auslösern definieren Sie, wann die konfigurierte Aufgabe gestartet wird. Sie haben hierbei die Wahl zwischen automatischer Ausführung zu bestimmten Zeitpunkten oder manuellem Start. Aktive Auslöser sind mit einem grünen Haken markiert.',
    'd3tbclusermanager_items_overview'                 => 'Übersicht',
    'd3tbclusermanager_items_overview_desc'             => 'Die Übersicht stellt Ihnen eine einfache Auswertung über die Aufgabe und die damit verbundenen Kundenkonten zur Verfügung. Weiterhin können Sie die Konfiguration der gewählten Aufgabe übersichtlich einsehen.',
    'd3tbclusermanager_items_requ'                     => 'Bedingungen',
    'd3tbclusermanager_items_requ_desc'                 => 'Mit den Bedingungen stellen Sie ein, welche Kundenkonten von dieser Aufgabe bearbeitet werden sollen. Wenn Sie mehrere Bedingungen wählen, müssen diese alle gemeinsam auf ein Kundenkonto passen.',
    'd3tbclusermanager_items_action'                   => 'Aktionen',
    'd3tbclusermanager_items_action_desc'               => 'Aktionen sind Veränderungen, welche auf die selektierten Kundenkonten angewendet werden. Die Ausführungsreihenfolge entspricht genau der Darstellung auf dieser Seite von oben nach unten.',
    'tbcluser_usermanager_jobs'                        => '<img src="https://logos.oxidmodule.com/d3logo.svg" alt="(D3)" style="height:1em;width:1em"> Kundenmanager',

    'D3_USERMANAGER_TRANSL'                            => 'Kundenmanager',

    'D3USERMANAGER_CONFIGVARS_SADDTITLE'               => 'Namenszusatz:',
    'D3USERMANAGER_CONFIGVARS_IEXECJOBSLIMIT'          => 'Anzahl ausführbarer Aufgaben:',

    'D3_USERMANAGER_SET_DEBUG_DESC'                    => 'Mit aktiviertem Debug-Modus werden die einzelnen Aufgaben nur am Bildschirm angezeigt und (unabhängig der Aufgabeneinstellung) nicht tatsächlich ausgeführt. Rufen Sie zur Kontrolle den Cronjob einfach über den weiter unten gezeigten Link im Browser auf und kontrollieren Sie die Ausgaben.',
    'D3_USERMANAGER_SET_CRON'                          => 'allgemeine Cronjob-Einstellungen',
    'D3_USERMANAGER_SET_CRON_ACTIVE'                   => 'Cronjob aktiv',
    'D3_USERMANAGER_SET_CRON_MAXUSERCNT'               => 'max. Kundenanzahl pro Cron-Durchlauf',
    'D3_USERMANAGER_SET_CRON_PASSWORD'                 => 'Zugriffspasswort',
    'D3_USERMANAGER_SET_CRON_PATH'                     => 'interner Cronaufruf',
    'D3_USERMANAGER_SET_CRON_PATH_DESC'                => 'Zur Einrichtung des Cronjobs auf dem Server verwenden Sie bitte diesen Aufruf. Alternativ können Sie sich auch ein Shell-Script erzeugen lassen, welches diesen Aufruf ebenfalls enthält.',
    'D3_USERMANAGER_SET_CRON_EXTLINK'                  => 'externer Link (abgekündigt zur automatischen Ausführung)',
    'D3_USERMANAGER_SET_CRON_EXTLINK_DESC'             => 'Möchten Sie den Cronjob manuell im Browser ausführen, verwenden Sie diesen Link. Dieser Aufruf wird zukünftig entfernt. Bitte verwenden Sie nur noch den internen Aufruf über die Serverkonsole.',
    'D3_USERMANAGER_SET_CRON_LASTEXEC'                 => 'letzte Ausführung',
    'D3_USERMANAGER_SET_CRON_JOBID'                    => 'Cronjobeinstellungen für Cronjob-ID "%1$s" -> %2$d zugeordnete Aufgabe',
    'D3_USERMANAGER_SET_CRON_JOBSID'                   => 'Cronjobeinstellungen für Cronjob-ID "%1$s" -> %2$d zugeordnete Aufgaben',
    'D3_USERMANAGER_SET_CRON_JOB_DESC'                 => '<p>Neu angelegte Aufgaben oder Aufgaben, denen Sie keine spezielle Cronjob-ID zugewiesen haben, stehen automatisch unter der Cronjob-ID 0 zur Verfügung. Hierfür können Sie mit den in den Modul-Grundeinstellungen angezeigten Daten einen Cronjob einrichten, der diese Aufgaben automatisch ausführt.<p><p>Möchten Sie einzelne Aufgaben statt dessen zu anderen Zeiten oder in anderen Intervallen starten, können Sie durch das Definieren einer anderen Cronjob-ID eine einzelne Aufgabe oder Aufgabengruppe gezielt über zusätzliche Cronjobs starten lassen. Die Cronjob-ID setzen Sie an jeder einzelnen Aufgabe. Für Aufgabengruppen setzen Sie die gleiche ID an mehreren Aufgaben. Sobald die ID dort gespeichert ist, sehen Sie in den Modul-Grundeinstellungen die nötigen Informationen für diese Cronjob-ID (<b>Cronjobeinstellungen mit Cronjob-ID X</b>). Damit können Sie den zusätzlichen Cronjob einrichten.</p><p>Weitere Informationen zur Verwendung der Cronjob-IDs finden Sie im Handbuch zum Modul.</p>',
    'D3_USERMANAGER_SET_JOBSETTINGS'                    => 'Aufgabeneinstellungen',
    'D3_USERMANAGER_SET_CALCULATESTATONDEMAND'          => 'statistische Daten zur Aufgabe einzeln und nur nach Anforderung berechnen',
    'D3_USERMANAGER_SET_CALCULATESTATONDEMAND_DESC'     => 'Für die Anzeige der statistischen Daten werden im entsprechenden Tab mehrere Datenbankabfragen ausgeführt. Bei Shops mit umfangreichen Kundendaten oder aufwändigen Aufgaben kann es sein, dass die Statistikdaten nicht einem Durchlauf ermittelt werden können. Die Seite kann dann nicht angezeigt werden. Durch diese Option werden die Daten einzeln und nur auf Anforderung ermittelt.',
    'D3_USERMANAGER_SET_FOLDER'                        => 'Ordner',
    'D3_USERMANAGER_SET_FOLDERLIST'                    => 'Ordner verwalten, um die Aufgaben zu gruppieren',
    'D3_USERMANAGER_SET_FOLDERLIST_DESC'               => 'Fügen Sie für einen neuen Ordner einen zusätzlichen Multilangbaustein zur Liste hinzu. Übersetzen Sie diesen in den Sprachdateien Ihres Shops.',

    'D3_USERMANAGER_USER_SELECTFOLDER'                => 'bitte Aufgabenordner wählen',
    'D3_USERMANAGER_USER_ALL'                         => '-- alle Aufgaben --',
    'D3_USERMANAGER_USER_NEW'                         => 'neue Aufgaben',
    'D3_USERMANAGER_USER_EXTRACTION'                  => 'Kundengewinnung',
    'D3_USERMANAGER_USER_RETENTION'                   => 'Kundenbindung',
    'D3_USERMANAGER_USER_MAINTENANCE'                 => 'Wartung',

    'D3_TOOLTIPS_NEWUSERMANAGER'                       => 'Neue Aufgabe anlegen',
    'D3_GENERAL_USERMANAGER_SAVE'                      => 'Speichern',
    'D3_GENERAL_USERMANAGER_COPY'                      => 'identische Kopie anlegen',
    'D3_GENERAL_USERMANAGER_COPY_PREFIX'               => 'Kopie von ',
    'D3_GENERAL_USERMANAGER_SELECT_ALL'                => 'alle Einträge wählen',
    'D3_GENERAL_USERMANAGER_SELECT_NONE'               => 'keinen Eintrag wählen',
    'D3_GENERAL_USERMANAGER_TASKCOUNT_CRONID'          => 'Anzahl Aufgaben für Cronjob-ID %1$s: %2$u',
    'D3_GENERAL_USERMANAGER_LASTEXEC_CRONID'           => 'letzte Ausführung für Cronjob-ID %1$s: %2$s',

    'D3_USERMANAGER_GENERAL_ACTIVTITLE'                => 'AC',
    'D3_USERMANAGER_GENERAL_ACTIVTITLE_DESC'           => 'Aktiv für automatische Ausführung über Cronjobs',
    'D3_USERMANAGER_GENERAL_ACTIVMANTITLE'             => 'AM',
    'D3_USERMANAGER_GENERAL_ACTIVMANTITLE_DESC'        => 'Aktiv für manuelle Ausführung',

    'D3_USERMANAGER_MAIN_FIELDSET_CRONJOB'             => 'zeitgesteuerter Cronjob',
    'D3_USERMANAGER_MAIN_FIELDSET_MANUALLY'            => 'manuelle Ausführung',
    'D3_USERMANAGER_MAIN_FIELDSET_AFTERORDERCOMPLETED' => 'nach dem Abschluss der Bestellung durch den Kunden',
    'D3_USERMANAGER_MAIN_FIELDSET_AFTERUSERSAVE'       => 'nach jedem Speichern des Benutzerkontos',

    'D3_USERMANAGER_MAIN_FIELDSET_ACTIVE'              => 'Aktivstatus',
    'D3_USERMANAGER_MAIN_FIELDSET_EXECUTION'           => 'Ausführung',
    'D3_USERMANAGER_MAIN_FIELDSET_FOLLOWUP'            => 'Wiedervorlage',

    'D3_USERMANAGER_MAIN_ACTIVE'                       => 'Aktiv für automatische Ausführung über Cronjob',
    'D3_USERMANAGER_MAIN_ACTIVE_DESC'                  => 'Setzt die aktuelle Aufgabe für die Ausführung per Cronjob aktiv. Auf die Option, diese Aufgabe manuell auszuführen, hat dieser Haken keinen Einfluss.',
    'D3_USERMANAGER_MAIN_CRONJOBID'                    => 'Cronjob-ID',
    'D3_USERMANAGER_MAIN_PREEXECUTESCRIPT'             => 'vorab ausgeführtes Script',
    'D3_USERMANAGER_MAIN_PREEXECUTESCRIPT_DESC'        => '<p>Direkt vor der Aufgabenausführung via Cronjob kann ein Script ausgeführt werden, welches vorbereitende Arbeiten durchführen kann.</p><p>Diese Angabe ist optional. Erwartet wird die Angabe einer statisch aufrufbaren Funktion inkl. deren vollständigen Klassennamens. Bsp.:<pre>\D3\Example\prePostExecute::preExecuteScript</pre> Als erster Parameter wird das Aufgabenobjekt (d3usermanager) übergeben.</p><p>Die Scriptausführung ist nur in der Premium-Edition des Moduls möglich. Lassen Sie Ihre Lizenz ggf. dafür erweitern.</p>',
    'D3_USERMANAGER_MAIN_POSTEXECUTESCRIPT'            => 'danach ausgeführtes Script',
    'D3_USERMANAGER_MAIN_POSTEXECUTESCRIPT_DESC'       => '<p>Direkt nach der Aufgabenausführung via Cronjob kann ein Script ausgeführt werden, welches nachbereitende Arbeiten durchführen kann.</p><p>Diese Angabe ist optional. Erwartet wird die Angabe einer statisch aufrufbaren Funktion inkl. deren vollständigen Klassennamens. Bsp.:<pre>\D3\Example\prePostExecute::postExecuteScript</pre> Als erster Parameter wird das Aufgabenobjekt (d3usermanager) übergeben.</p><p>Die Scriptausführung ist nur in der Premium-Edition des Moduls möglich. Lassen Sie Ihre Lizenz ggf. dafür erweitern.</p>',
    'D3_USERMANAGER_MAIN_ACTIVFROMTILL'                => 'Oder für Cronjobausführung aktiv',
    'D3_USERMANAGER_MAIN_ACTIVEFROM'                   => 'von',
    'D3_USERMANAGER_MAIN_ACTIVETO'                     => 'bis',
    'D3_USERMANAGER_MAIN_EXECUTE2'                     => 'Aufgabenausführung nur simulieren',
    'D3_USERMANAGER_MAIN_EXECUTE_DEBUG'                => '(modulweiter Debug-Modus verhindert aktuell die Ausführung)',
    'D3_USERMANAGER_MAIN_EXECUTE_DESC'                 => 'Definierte Aktionen werden nicht ausgeführt. Haben Sie zum Beispiel für diese Aufgabe eingestellt, dass alle betroffenen Kunden gelöscht werden sollen, sind diese nach Beendigung der Aufgabe sonst tatsächlich nicht mehr vorhanden. Der modulweit einstellbare "Debug-Modus" verhindert diese Ausführung unabhängig dieser Einstellung.',
    'D3_USERMANAGER_MAIN_MAILSEND'                     => 'Infomail an Shopbetreiber senden',
    'D3_USERMANAGER_MAIN_MAILSEND_DESC'                => 'Diese Option sendet nach Beendigung der Abarbeitung eine Mail an die Shopbetreiberadresse mit einer Aufstellung, welche Aufgaben ausgeführt wurden oder werden sollen. Auch eventuelle Fehler werden darin aufgeführt. Ob die Ausgaben wirklich ausgeführt werden, stellen Sie am entsprechend benannten Schalter ein. Ist dieser Haken nicht gesetzt, wird keine Info gesendet. Infos über die Aufgabenausführung finden Sie (je nach Einstellung der Log-Level) auch im Logging des Modul-Connectors. Dort können Sie ebenfalls Einstellungen zur regelmäßige Information per E-Mail einstellen. Details dazu finden Sie im Rahmen des Modul-Connectors.',
    'D3_USERMANAGER_MAIN_ADDHISTORYITEM'               => 'bei jeder Ausführung Historie-Eintrag am Kundenkonto ablegen',
    'D3_USERMANAGER_MAIN_ADDHISTORYITEM_DESC'          => 'Nach der Ausführung wird an jedem betroffenen Kundenkonto ein Eintrag in die Historie eingefügt. Dieser Eintrag enthält Informationen zu den ausgeführten Aktionen. Die Historieneinträge sind dann sinnvoll, wenn die Aktionen protokolliert werden sollen oder die Ausführung kontrolliert werden soll.',
    'D3_USERMANAGER_MAIN_EXECMANUALLY'                 => 'Aktiv für manuelle Ausführung am Kundenkonto',
    'D3_USERMANAGER_MAIN_EXECMANUALLY_DESC'            => 'Ist dieser Haken gesetzt, finden Sie diese Aufgabe auswählbar auch in der Kundenübersicht des Shops. Dort können Sie die Aufgabe auch manuell für jeden Kunden starten bzw. deren Ausführungsstatus zurücksetzen.',
    'D3_USERMANAGER_MAIN_EXECMANUALLYMEETCONDITION'    => 'Aufgabe wird nur bei Kundenkonten angeboten, bei denen die eingestellten Bedingungen erfüllt sind',
    'D3_USERMANAGER_MAIN_EXECMANUALLYMEETCONDITION_DESC'=> 'Ohne diesen Haken wird diese Aufgabe an allen Kundenkonten gezeigt, auch wenn diese nicht zu den Bedingungen passen. Diese werden auch später zur Ausführung nicht mehr geprüft.',
    'D3_USERMANAGER_MAIN_EXECORDERFINISHTRIGGERED'     => 'Ausführung nach Bestellabschluss möglich',
    'D3_USERMANAGER_MAIN_EXECORDERFINISHTRIGGERED_DESC'=> 'Ist dieser Haken gesetzt, wird diese Aufgabe ausgeführt, wenn eine Bestellung durch den Kunden abgeschlossen wurde und diese den gesetzten Bedingungen der Aufgabe entspricht.',
    'D3_USERMANAGER_MAIN_EXECUSERSAVETRIGGERED'        => 'Ausführung nach jedem Speichern eines Kundenkontos möglich',
    'D3_USERMANAGER_MAIN_EXECUSERSAVETRIGGERED_DESC'   => 'Ist dieser Haken gesetzt, wird diese Aufgabe ausgeführt, wenn eine Kundenkonto gespeichert wird. Dies passiert beim Registrieren des Kunden und auch beim Bearbeiten im Adminbereich. Das Kundenkonto muss den gesetzten Bedingungen der Aufgabe entsprechen.',
    'D3_USERMANAGER_MAIN_MARKUSER'                     => 'Bearbeitete Kunden <b>nicht</b> als erledigt markieren',
    'D3_USERMANAGER_MAIN_MARKUSER_DESC'                => 'Diese Kundenkonten werden beim nächsten Durchlauf also wieder bearbeitet, wenn die Bedingungen mit den Kundeneinstellungen übereinstimmt. Dies kann für Wiedervorlagen hilfreich sein.',
    'D3_USERMANAGER_MAIN_UNMARKEDEXECDELAY'            => 'Auftrag pausiert nach Ausführung für mindestens...',
    'D3_USERMANAGER_MAIN_UNMARKEDEXECDELAY_DAY'        => 'Tag(e)',
    'D3_USERMANAGER_MAIN_UNMARKEDEXECDELAY_HOUR'       => 'Stunde(n)',
    'D3_USERMANAGER_MAIN_UNMARKEDEXECDELAY_MINUTE'     => 'Minute(n)',
    'D3_USERMANAGER_MAIN_UNMARKEDEXECDELAY_DESC'       => 'Werden Aufträge nicht als "abgearbeitet" markiert, würden diese bei jedem Cronjob-Start erneut ausgeführt werden. Ist dies jedoch so häufig nicht gewünscht, kann der Auftrag für eine gewisse Zeit pausieren. Dieser Zeitabstand zwischen 2 Ausführungen kann hier eingestellt werden.<br><br>Beachten Sie jedoch, dass der Auftrag nur so häufig ausgeführt werden kann, wie auch das Cronscript gestartet wird.',
    'D3_USERMANAGER_MAIN_TITLE'                        => 'Titel',
    'D3_GENERAL_USERMANAGER_TITLE'                     => 'Titel',
    'D3_USERMANAGER_MAIN_SORT'                         => 'Reihenfolge',
    'D3_USERMANAGER_MAIN_SORT_DESC'                    => 'Die Reihenfolge legt fest, wann und eben in welcher Reihenfolge die Aufgaben ausgeführt werden. Diese Einstellung ist besonders wichtig, wenn die Aufgaben aufeinander aufbauen. Aufgaben mit kleiner Sortiernummer werden vor Aufgaben mit hoher Sortiernummer ausgeführt.',
    'D3_USERMANAGER_MAIN_FOLDER'                       => 'Ordner',
    'D3_USERMANAGER_MAIN_LASTEXEC'                     => 'zuletzt ausgeführt:',
    'D3_GENERAL_USERMANAGER_SORT'                      => 'Reihenfolge',
    'D3_GENERAL_USERMANAGER_CRONID'                    => 'Cronjob-ID',

    'D3_GENERAL_USERMANAGER_BASICRESTRICTIONS'         => 'Für Test-/Dev-Installation sind globale Bedingungen gesetzt, die nur bestimmte Bestellungen verfügbar machen. Ändern Sie diese Einstellungen bei Bedarf in der config.inc.php des Shops.',
    'D3_GENERAL_USERMANAGER_DESCRIPTION'               => 'Beschreibung',

    'D3_USERMANAGER_OVERVIEW_STAT'                     => 'Statistik',
    'D3_USERMANAGER_OVERVIEW_REQU'                     => 'Bedingungen',
    'D3_USERMANAGER_OVERVIEW_ACTION'                   => 'Aktionen',
    'D3_USERMANAGER_OVERVIEW_NOREQUEST'                => 'keine (in Ihrer Lizenz gültigen) Bedingungen definiert',
    'D3_USERMANAGER_OVERVIEW_NOACTION'                 => 'keine (in Ihrer Lizenz gültigen) Aktionen definiert',

    'D3_USERMANAGER_REQU'                              => 'Kundenmanager - Bedingungen',
    'D3_USERMANAGER_REQU_REGISTERED_DATE'              => '(Datum im Format \'%1$s\')',
    'D3_USERMANAGER_REQU_ACCOUNT'                      => 'aus Kundenkonto',
    'D3_USERMANAGER_REQU_ACTIVEUSER'                   => 'Aktivhaken',
    'D3_USERMANAGER_REQU_ACTIVEUSER_ERR_UNVALIDTYPE'   => 'kein gültiger Status gewählt',
    'D3_USERMANAGER_REQU_REGISTERUSERFROM'             => 'Registrierdatum nach',
    'D3_USERMANAGER_REQU_REGISTERUSERFROM_ERR_UNVALID' => 'kein gültiger Vergleichswert gesetzt',
    'D3_USERMANAGER_REQU_REGISTERUSERTO'               => 'Registrierdatum vor',
    'D3_USERMANAGER_REQU_REGISTERUSERTO_ERR_UNVALID'   => 'kein gültiger Vergleichswert gesetzt',
    'D3_USERMANAGER_REQU_REGISTERTIMESPAN'             => 'Zeitpunkt des Registrierdatums',
    'D3_USERMANAGER_REQU_REGISTERTIMESPAN_MINIMUM'     => 'älter als',
    'D3_USERMANAGER_REQU_REGISTERTIMESPAN_MAXIMUM'     => 'jünger als',
    'D3_USERMANAGER_REQU_REGISTERTIMESPAN_ERR_UNVALIDUNIT' => 'keine gültige Einheit gesetzt',
    'D3_USERMANAGER_REQU_REGISTERTIMESPAN_ERR_UNVALIDTYPE' => 'kein gültiger Typ gesetzt',
    'D3_USERMANAGER_REQU_REGISTERTIMESPAN_ERR_UNVALIDVALUE' => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_TIMESPAN_MINUTE'              => 'Minute(n)',
    'D3_USERMANAGER_REQU_TIMESPAN_HOUR'                => 'Stunde(n)',
    'D3_USERMANAGER_REQU_TIMESPAN_DAY'                 => 'Tag(e)',
    'D3_USERMANAGER_REQU_FROMUSERNR'                   => 'Kundennummer größer / gleich',
    'D3_USERMANAGER_REQU_FROMUSERNR_ERR_UNVALID'       => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_TOUSERNR'                     => 'Kundennummer kleiner / gleich',
    'D3_USERMANAGER_REQU_TOUSERNR_ERR_UNVALID'         => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_PASSWORDUSER'                 => 'Passwort',
    'D3_USERMANAGER_REQU_PASSWORDUSER_ERR_UNVALID'     => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_NOPASSWORDUSER'               => 'hat <b>kein</b> Passwort',
    'D3_USERMANAGER_REQU_INGROUP'                      => 'in Kundengruppe',
    'D3_USERMANAGER_REQU_INGROUP_ERR_UNVALID'          => 'keine gültige Kundengruppe gesetzt',
    'D3_USERMANAGER_REQU_NOTINGROUP'                   => '<b>nicht</b> in Kundengruppe',
    'D3_USERMANAGER_REQU_NOTINGROUP_ERR_UNVALID'       => 'keine gültige Kundengruppe gesetzt',
    'D3_USERMANAGER_REQU_NEWSLETTERUSER'               => 'Newsletterempfang',
    'D3_USERMANAGER_REQU_NEWSLETTERUSER_ERR_UNVALID'   => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_HASBIRTHDAY'                  => 'hat Geburtstag',
    'D3_USERMANAGER_REQU_HASBIRTHDAY_DESC'             => 'Es wird der Kunde gewählt, der zum Ausführungszeitpunkt des Auftrages Geburtstag hat. Wann Sie diese Option setzen, ist dagegen unrelevant. Um keine Kunden von dieser Aufgabe auszuschließen, sollte diese mindestens einmal an jedem Tag gestartet werden.',
    'D3_USERMANAGER_REQU_AGECHECK'                     => 'Alter',
    'D3_USERMANAGER_REQU_AGECHECK_YEARS'               => 'Jahre',
    'D3_USERMANAGER_REQU_AGECHECK_ERR_UNVALIDTYPE'     => 'kein gültiger Vergleichstyp gesetzt',
    'D3_USERMANAGER_REQU_AGECHECK_ERR_UNVALIDVALUE'    => 'kein gültiger Vergleichswert gesetzt',
    'D3_USERMANAGER_REQU_BIRTHDATEUSERFROM'            => 'Geburtsdatum nach',
    'D3_USERMANAGER_REQU_BIRTHDATEUSERFROM_ERR_UNVALID'=> 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_BIRTHDATEUSERTO'              => 'Geburtsdatum vor',
    'D3_USERMANAGER_REQU_BIRTHDATEUSERTO_ERR_UNVALID'  => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_VALIDMAIL'                    => 'Newsletter-Mailadresse',
    'D3_USERMANAGER_REQU_VALIDMAIL_ERR_UNVALID'        => 'kein gültiger Vergleich gesetzt',
    'D3_USERMANAGER_REQU_VALIDMAIL_DESC'               => 'Die Gültigkeit der Mailadresse wird nur geprüft, wenn ein Newsletter an den Kunden versandt wurde und die Gültigkeitsinfomation wieder an den Shop zurückgemeldet wurde. Ansonsten werden Mailadressen immer als gültig angesehen.',
    'D3_USERMANAGER_REQU_VALIDMAIL_VALID'              => 'gültig',
    'D3_USERMANAGER_REQU_VALIDMAIL_NOTVALID'           => '<b>nicht</b> gültig',
    'D3_USERMANAGER_REQU_BONI'                          => 'Bonität',
    'D3_USERMANAGER_REQU_BONI_DESC'                     => 'Bonitätswerte werden i.d.R. von externen Diensten bereitgestellt und als Ganzzahl am Kundenkonto gespeichert. Tragen Sie hier den gewünschten Schwellenwert der Bonitätsprüfung ein. Abhängig davon, ob ein hoher Bonitätsindex gut oder schlecht ist, definieren Sie dann die Filterrichtung.',
    'D3_USERMANAGER_REQU_BONI_ERR_UNVALIDTYPE'         => 'kein gültiger Vergleichstyp gesetzt',
    'D3_USERMANAGER_REQU_BONI_ERR_UNVALIDVALUE'        => 'kein gültiger Vergleichswert gesetzt',
    'D3_USERMANAGER_REQU_DELIVERYADDRESS'               => 'Lieferadresse',
    'D3_USERMANAGER_REQU_DELIVERYADDRESS_DESC'          => 'Diese Option prüft ausschließlich auf gesetzte Lieferadresse. Ob diese auch schon einmal verwendet wurde(n), wird nicht geprüft.',
    'D3_USERMANAGER_REQU_DELIVERYADDRESS_ERR_UNVALID'   => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_USEREXECUTEMETHOD'             => 'Methode des Kundenlistenobjekts ausführen',
    'D3_USERMANAGER_REQU_USEREXECUTEMETHOD_NAME'        => 'Methodenname',
    'D3_USERMANAGER_REQU_USEREXECUTEMETHOD_DESC'        => '<p>Geben Sie hier ausschließlich den Namen der Methode an. Parameter oder Klammern dürfen nicht verwendet werden.</p><p>Die Methode muss "public" am Kundenlistenobjekt ("oxuserlist" und deren Erweiterungen) existieren. Der Methodenaufruf erfolgt <b>nicht</b> statisch.</p><p>Innerhalb der Methode kann das oxUserList-Objekt beliebig manipuliert werden. Eine Rückgabe der Kundenliste ist nicht erforderlich.</p><p>Diese Parameter werden der Methode übergeben: <ul><li>aktuell verwendetes Kundenmanagerauftragsobjekt ("d3usermanager" bzw. dessen Überladung)</li></ul></p><p>Ein Rückgabewert wird nicht verarbeitet.</p>',
    'D3_USERMANAGER_REQU_USEREXECUTEMETHOD_ERR_UNVALID' => 'keine gültige Methode gesetzt',
    'D3_USERMANAGER_REQU_INVADR'                        => 'aus Rechnungsadresse',
    'D3_USERMANAGER_REQU_INV_GENDER'                    => 'Geschlecht (Rechnungsadr.)',
    'D3_USERMANAGER_REQU_GENDER_MR'                     => 'männlich',
    'D3_USERMANAGER_REQU_GENDER_MRS'                    => 'weiblich',
    'D3_USERMANAGER_REQU_INV_GENDER_ERR_UNVALID'        => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_INVCOUNTRY'                    => 'Land (Rechnungsadr.)',
    'D3_USERMANAGER_REQU_INVCOUNTRY_ERR_UNVALID'        => 'kein gültiges Land gewählt',
    'D3_USERMANAGER_REQU_INVZIPRANGE'                   => 'PLZ-Bereich (Rechnungsadr.)',
    'D3_USERMANAGER_REQU_INVZIPRANGEFROM'               => 'von',
    'D3_USERMANAGER_REQU_INVZIPRANGETO'                 => 'bis',
    'D3_USERMANAGER_REQU_INVZIPRANGE_ERR_UNVALID'       => 'kein gültiger Postleitzahlenbereich gesetzt',
    'D3_USERMANAGER_REQU_INVCOMPANY'                    => 'Firmenname (Rechnungsadr.)',
    'D3_USERMANAGER_REQU_INVCOMPANY_ERR_UNVALID'        => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_INVUSTID'                      => 'Umsatzsteuer-ID (Rechnungsadr.)',
    'D3_USERMANAGER_REQU_INVUSTID_ERR_UNVALID'          => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUE'             => 'Adressfeld auf Wert prüfen (Rechnungsadr.)',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUE_FIELD'       => 'Feldname',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUE_FIELD_DESC'    => 'Dieser Filter prüft auf ein frei definierbares Feld der "oxuser"-Datenbanktabelle. Tragen Sie hier den tatsächlichen Namen des zu prüfenden Feldes ein. Soll auf Inhalt in Sprachfeldern (*_1) geprüft werden, ist hier die Angabe des Multilang-Namens erforderlich.',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUE_ERR_UNVALIDFIELD' => 'kein gültiges Feld gewählt',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUETYPE_CONTENT' => 'enthält Wert:',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUETYPE_EMPTY'   => 'ist leer',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUETYPE_NOTEMPTY'=> 'ist nicht leer',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUE_ERR_UNVALIDTYPE' => 'kein gültiger Typ gewählt',
    'D3_USERMANAGER_REQU_INVUSERFIELDVALUE_ERR_UNVALIDVALUE' => 'kein gültiger Wert gewählt',
    'D3_USERMANAGER_REQU_ARTICLECONTENT2_DESC'          => 'Wählen Sie das zu prüfende Feld und tragen Sie das Suchmuster zur Prüfung ein. Dabei sind folgende Wildcards erlaubt:<ul><li>[ <b>_</b> ] ein einzelnes Zeichen, auch leer</li><li>[ <b>%</b> ] beliebig viele Zeichen</li></ul>Um die genannten Zeichen als Suchbegriff zu verwenden, maskieren Sie diese mit einem Schrägstrich [ <b>/</b> ]. <br><br>Beispiele: <br>"__shirt_" findet "Shirts", aber auch "T-Shirt"<br>"%tasse%" findet alle Arten von Tassen<br><br>Die Groß-/Kleinschreibung ist hierbei egal. Legen Sie die Prüfung so an, dass alle Sprachmöglichkeiten Ihres Shops abgedeckt werden.',
    'D3_USERMANAGER_REQU_DELADR'                        => 'aus Lieferadresse(n)',
    'D3_USERMANAGER_REQU_DELADR_GENERALDESC'            => 'Für die Optionen an den Lieferadressen ist ausschlaggebend, dass die Daten in mindestens einer verwendeten Lieferadresse vorkommen. Ob nur eine oder mehrere zutreffende Lieferadressen verwendet wurden, wird nicht berücksichtigt.<br>Wählen Sie das zu prüfende Feld und tragen Sie das Suchmuster zur Prüfung ein. Dabei sind folgende Wildcards erlaubt:<ul><li>[ <b>_</b> ] ein einzelnes Zeichen, auch leer</li><li>[ <b>%</b> ] beliebig viele Zeichen</li></ul>Um die genannten Zeichen als Suchbegriff zu verwenden, maskieren Sie diese mit einem Schrägstrich [ <b>/</b> ]. <br><br>Beispiele: <br>"__shirt_" findet "Shirts", aber auch "T-Shirt"<br>"%tasse%" findet alle Arten von Tassen<br><br>Die Groß-/Kleinschreibung ist hierbei egal. Legen Sie die Prüfung so an, dass alle Sprachmöglichkeiten Ihres Shops abgedeckt werden.',
    'D3_USERMANAGER_REQU_DEL_GENDER'                    => 'Geschlecht (Lieferadr.)',
    'D3_USERMANAGER_REQU_DEL_GENDER_ERR_UNVALID'        => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_DELCOUNTRY'                    => 'Land  (Lieferadr.)',
    'D3_USERMANAGER_REQU_DELCOUNTRY_ERR_UNVALID'        => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_DELZIPRANGE'                   => 'PLZ-Bereich (Lieferadr.)',
    'D3_USERMANAGER_REQU_DELZIPRANGE_ERR_UNVALID'       => 'keine gültiger Postleitzahlenbereich gesetzt',
    'D3_USERMANAGER_REQU_DELCOMPANY'                    => 'Firmenname (Lieferadr.)',
    'D3_USERMANAGER_REQU_DELCOMPANY_ERR_UNVALID'        => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_DELUSTID'                      => 'Umsatzsteuer-ID (Lieferadr.)',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUE'             => 'Adressfeld auf Wert prüfen (Lieferadr.)',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUE_FIELD'       => 'Feldname',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUE_FIELD_DESC'    => 'Dieser Filter prüft auf ein frei definierbares Feld der "oxaddress"-Datenbanktabelle. Tragen Sie hier den tatsächlichen Namen des zu prüfenden Feldes ein. Soll auf Inhalt in Sprachfeldern (*_1) geprüft werden, ist hier die Angabe des Multilang-Namens erforderlich.',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUE_ERR_UNVALIDFIELD' => 'kein gültiges Feld gewählt',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUE_ERR_UNVALIDTYPE' => 'kein gültiger Inhaltstyp gewählt',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUE_ERR_UNVALIDVALUE' => 'kein gültiger Inhalt gesetzt',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUETYPE_CONTENT' => 'enthält Wert:',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUETYPE_EMPTY'   => 'ist leer',
    'D3_USERMANAGER_REQU_DELUSERFIELDVALUETYPE_NOTEMPTY'=> 'ist nicht leer',

    'D3_USERMANAGER_REQU_ORDERS'                        => 'aus Bestellungen',
    'D3_USERMANAGER_REQU_ORDER_GENERALDESC'             => 'Für die Optionen an den Bestellungen ist ausschlaggebend, dass die Daten in mindestens einer verwendeten Bestellung vorkommen. Ob nur eine oder mehrere zutreffende Bestellungen verwendet wurden, wird nicht berücksichtigt.<br>Wählen Sie das zu prüfende Feld und tragen Sie das Suchmuster zur Prüfung ein. Dabei sind folgende Wildcards erlaubt:<ul><li>[ <b>_</b> ] ein einzelnes Zeichen, auch leer</li><li>[ <b>%</b> ] beliebig viele Zeichen</li></ul>Um die genannten Zeichen als Suchbegriff zu verwenden, maskieren Sie diese mit einem Schrägstrich [ <b>/</b> ]. <br><br>Beispiele: <br>"__shirt_" findet "Shirts", aber auch "T-Shirt"<br>"%tasse%" findet alle Arten von Tassen<br><br>Die Groß-/Kleinschreibung ist hierbei egal. Legen Sie die Prüfung so an, dass alle Sprachmöglichkeiten Ihres Shops abgedeckt werden.',
    'D3_USERMANAGER_REQU_HASNOORDERS'                   => 'hat keine Bestellungen',
    'D3_USERMANAGER_REQU_MINORDERCOUNT'                 => 'Mindestanzahl Bestellungen',
    'D3_USERMANAGER_REQU_MAXORDERCOUNT'                 => 'Höchstanzahl Bestellungen',
    'D3_USERMANAGER_REQU_MAXORDERCOUNT_ERR_UNVALID'     => 'keine gültige Anzahl gesetzt',
    'D3_USERMANAGER_REQU_MINORDERCOUNT_ERR_UNVALID'     => 'keine gültige Anzahl gesetzt',
    'D3_USERMANAGER_REQU_MINORDERSUM'                   => ' aller Bestellungen größer als',
    'D3_USERMANAGER_REQU_MAXORDERSUM'                   => ' aller Bestellungen kleiner als',
    'D3_USERMANAGER_REQU_ORDERSUMTYPE_TOTALNET'         => 'Artikelnettosumme',
    'D3_USERMANAGER_REQU_ORDERSUMTYPE_TOTALBRUT'        => 'Artikelbruttosumme',
    'D3_USERMANAGER_REQU_ORDERSUMTYPE_TOTALORDER'       => 'Gesamtsumme',
    'D3_USERMANAGER_REQU_ORDERSUMTYPE_DEL'              => 'Versandkosten',
    'D3_USERMANAGER_REQU_ORDERSUMTYPE_PAY'              => 'Zahlartkosten',
    'D3_USERMANAGER_REQU_MAXORDERSUM_ERR_UNVALIDTYPE'   => 'kein gültiger Typ gewählt',
    'D3_USERMANAGER_REQU_MAXORDERSUM_ERR_UNVALIDVALUE'  => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_MINORDERSUM_ERR_UNVALIDTYPE'   => 'kein gültiger Typ gewählt',
    'D3_USERMANAGER_REQU_MINORDERSUM_ERR_UNVALIDVALUE'  => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_ORDERSUM_DEFCUR'               => '(in Shop-Basiswährung)',
    'D3_USERMANAGER_REQU_ORDERMINTIMESPAN'              => 'Bestellzeit',
    'D3_USERMANAGER_REQU_ORDERMAXTIMESPAN'              => 'Bestellzeit',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN'                 => 'Bestellzeit',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN_FIRST'           => 'erste',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN_LAST'            => 'letzte',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN_ERR_UNVALIDORDERTYPE' => 'kein gültiger Datumstyp gesetzt',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN_ERR_UNVALIDTYPE' => 'kein gültiger Typ gesetzt',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN_ERR_UNVALIDUNIT' => 'keine gültige Einheit gesetzt',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN_ERR_UNVALID'     => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_ORDERMAXTIMESPAN_ERR_UNVALIDUNIT' => 'keine gültige Einheit gesetzt',
    'D3_USERMANAGER_REQU_ORDERMAXTIMESPAN_ERR_UNVALIDVALUE' => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_ORDERMINTIMESPAN_ERR_UNVALIDUNIT' => 'keine gültige Einheit gesetzt',
    'D3_USERMANAGER_REQU_ORDERMINTIMESPAN_ERR_UNVALIDVALUE' => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_ORDERMINIMUMTIMESPAN'          => 'älter als',
    'D3_USERMANAGER_REQU_ORDERMAXIMUMTIMESPAN'          => 'jünger als',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN_MINIMUM'         => 'älter als',
    'D3_USERMANAGER_REQU_ORDERTIMESPAN_MAXIMUM'         => 'jünger als',
    'D3_USERMANAGER_REQU_ORDERLANGUAGE'                 => 'in Sprache',
    'D3_USERMANAGER_REQU_ORDERLANGUAGE_ERR_UNVALID'     => 'keine gültige Sprache gewählt',
    'D3_USERMANAGER_REQU_VOUCHER'                       => 'Gutschein(e)',
    'D3_USERMANAGER_REQU_VOUCHER_DESC'                  => 'Für diese Einstellung ist unerheblich, ob besonders viele Gutscheine, welche Arten von Gutscheinen eingelöst wurden oder mit welcher Bestellung. Ausschlag gebend ist ausschließlich, ob überhaupt schon einmal Gutscheine genutzt wurden.',
    'D3_USERMANAGER_REQU_VOUCHER_USED'                  => 'verwendet',
    'D3_USERMANAGER_REQU_VOUCHER_NOTUSED'               => '<b>nicht</b> verwendet',
    'D3_USERMANAGER_REQU_VOUCHER_ERR_UNVALID'           => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_VOUCHERNUMBER'                 => 'verwendete Gutscheinnummer',
    'D3_USERMANAGER_REQU_VOUCHERNUMBER_ERR_UNVALID'     => 'keine gültige Gutscheinnummer gesetzt',
    'D3_USERMANAGER_REQU_VOUCHERSERIE'                  => 'verwendete Gutscheinserie',
    'D3_USERMANAGER_REQU_VOUCHERSERIE_ERR_UNVALID'      => 'keine gültige Gutscheinserie gesetzt',
    'D3_USERMANAGER_REQU_VOUCHERSERIE_DESC'             => 'Tragen Sie hier bitte den aktuellen und eindeutigen Namen der zu prüfenden Gutscheinserie ein. Verwendet wird immer der Name in der ersten Shopsprache ("oxserienr"). Haben Sie den Namen der Gutscheinserie zwischenzeitlich geändert, verwenden Sie bitte den derzeitig aktuellen Namen. Geprüft werden können nur existierende Serien. Haben Sie eine Gutscheinserie gelöscht, können deren Gutscheine nur noch ausschließlich über die Gutscheinnummer gefunden werden. Eine Seriensuche ist dann leider nicht mehr möglich.',
    'D3_USERMANAGER_REQU_ORDERPAYMENT'                  => 'verwendete Zahlart',
    'D3_USERMANAGER_REQU_ORDERPAYMENT_ERR_UNVALID'      => 'keine gültige Zahlart gewählt',
    'D3_USERMANAGER_REQU_ORDERDELIVERY'                 => 'verwendete Versandart',
    'D3_USERMANAGER_REQU_ORDERDELIVERY_ERR_UNVALID'     => 'keine gültige Versandart gewählt',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUE'               => 'Bestellungsfeld auf Wert prüfen',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUE_FIELD'         => 'Feldname',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUE_FIELD_DESC'    => 'Dieser Filter prüft auf ein frei definierbares Feld der "oxorder"-Datenbanktabelle. Tragen Sie hier den tatsächlichen Namen des zu prüfenden Feldes ein. Soll auf Inhalt in Sprachfeldern (*_1) geprüft werden, ist hier die Angabe des Multilang-Namens erforderlich.',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUE_FIELD_ERR_UNVALIDFIELD' => 'kein gültiges Feld gewählt',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUETYPE_CONTENT'   => 'enthält Wert:',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUETYPE_EMPTY'     => 'ist leer',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUETYPE_NOTEMPTY'  => 'ist nicht leer',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUETYPE_ERR_UNVALIDTYPE' => 'kein gültiger Typ gewählt',
    'D3_USERMANAGER_REQU_ORDERFIELDVALUETYPE_ERR_UNVALIDVALUE' => 'kein gültiger Wert gewählt',
    'D3_USERMANAGER_REQU_OTHERJOB'                      => 'andere Aufgabe',
    'D3_USERMANAGER_REQU_OTHERJOB_NAME'                 => 'Aufgabe',
    'D3_USERMANAGER_REQU_OTHERJOB_UNKNOWNJOBID'         => 'Unbekannte Aufgabe',
    'D3_USERMANAGER_REQU_OTHERJOB_EXECUTED'             => 'ausgeführt',
    'D3_USERMANAGER_REQU_OTHERJOB_NOTEXECUTED'          => 'nicht ausgeführt',
    'D3_USERMANAGER_REQU_OTHERJOB_DESC'                 => 'Stellen Sie hier die Aufgabe des Kundenmanagers ein, deren Ausführungsstatus an den vorliegenden Kundenkonten geprüft werden sollen.',
    'D3_USERMANAGER_REQU_OTHERJOB_ERR_UNVALIDTYPE'      => 'kein gültiger Ausführungstyp gesetzt',
    'D3_USERMANAGER_REQU_OTHERJOB_ERR_UNVALIDVALUE'     => 'keine gültige Aufgabe gesetzt',

    'D3_USERMANAGER_REQU_USERBASKETS'                   => 'aus gespeicherten Warenkörben',
    'D3_USERMANAGER_REQU_USERBASKET'                    => 'gespeicherter Warenkorb',
    'D3_USERMANAGER_REQU_USERBASKET_ERR_UNVALID'        => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_USERBASKETFROM'                => 'gespeicherter Warenkorb nach (einschließlich)',
    'D3_USERMANAGER_REQU_USERBASKETFROM_ERR_UNVALID'    => 'kein gültiger Vergleichswert gesetzt',
    'D3_USERMANAGER_REQU_USERBASKETTO'                  => 'gespeicherter Warenkorb vor',
    'D3_USERMANAGER_REQU_USERBASKETTO_ERR_UNVALID'      => 'kein gültiger Vergleichswert gesetzt',
    'D3_USERMANAGER_REQU_USERBASKETTIMESPAN'            => 'Zeitraum ab letzter Änderung des gespeicherten Warenkorbes',
    'D3_USERMANAGER_REQU_USERBASKETTIMESPAN_ERR_UNVALIDUNIT' => 'keine gültige Einheit gesetzt',
    'D3_USERMANAGER_REQU_USERBASKETTIMESPAN_ERR_UNVALIDTYP' => 'kein gültiger Typ gesetzt',
    'D3_USERMANAGER_REQU_USERBASKETTIMESPAN_ERR_UNVALIDVALUE' => 'kein gültiger Wert gesetzt',
    'D3_USERMANAGER_REQU_USERBASKET_DATE'               => '(Datum im Format \'%1$s\')',
    'D3_USERMANAGER_REQU_NOTICELIST'                    => 'gespeicherter Notizzettel',
    'D3_USERMANAGER_REQU_NOTICELIST_ERR_UNVALID'        => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_NOTICELISTCOUNT'               => 'Anzahl gespeicherter Notizzettel',
    'D3_USERMANAGER_REQU_NOTICELISTCOUNT_VALUE'         => 'Stück',
    'D3_USERMANAGER_REQU_WISHLIST'                      => 'gespeicherter Wunschzettel',
    'D3_USERMANAGER_REQU_WISHLIST_ERR_UNVALID'          => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_REQU_WISHLISTCOUNT'                 => 'Anzahl gespeicherter Wunschzettel',
    'D3_USERMANAGER_REQU_WISHLISTCOUNT_VALUE'           => 'Stück',

    'D3_USERMANAGER_REQU_INDIV'                         => 'aus Individualbedingungen',
    'D3_USERMANAGER_REQU_USERFIELDVALUE_VALUE'          => 'Feldwert',

    'D3_USERMANAGER_REQU_MULTIPLE'                      => '(Mehrfachauswahl mit gedrückter Strg-Taste möglich)',

    'D3_USERMANAGER_REQU_GENERAL_LESSEQUAL'             => 'kleiner / gleich',
    'D3_USERMANAGER_REQU_GENERAL_HIGHEREQUAL'           => 'größer / gleich',
    'D3_USERMANAGER_REQU_GENERAL_SET'                  => 'gesetzt',
    'D3_USERMANAGER_REQU_GENERAL_NOTSET'               => '<b>nicht</b> gesetzt',
    'D3_USERMANAGER_REQU_GENERAL_EXIST'                => 'vorhanden',
    'D3_USERMANAGER_REQU_GENERAL_NOTEXIST'             => '<b>nicht</b> vorhanden',

    'D3_USERMANAGER_ACTION'                             => 'Kundenmanager - Aktionen',
    'D3_USERMANAGER_ACTION_CUSTOMER'                    => 'für Kunde',
    'D3_USERMANAGER_ACTION_CUSTOMERADD2GROUP'           => 'in Gruppe zuordnen',
    'D3_USERMANAGER_ACTION_CUSTOMERADD2GROUP_ERR_INVALID' => 'keine gültige Gruppe gewählt',
    'D3_USERMANAGER_ACTION_CUSTOMERREMOVEFROMGROUP'     => 'aus Gruppe entfernen',
    'D3_USERMANAGER_ACTION_CUSTOMERREMOVEFROMGROUP_ERR_INVALID'     => 'keine gültige Gruppe gewählt',
    'D3_USERMANAGER_ACTION_CUSTACTIVATE'                => 'Aktivhaken',
    'D3_USERMANAGER_ACTION_CUSTACTIVATE_ERR_INVALID'    => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_ACTION_GENERAL_SET'                 => 'setzen',
    'D3_USERMANAGER_ACTION_GENERAL_NOTSET'              => 'entfernen',
    'D3_USERMANAGER_ACTION_CUSTDELETE'                  => 'Kundenkonto löschen',
    'D3_USERMANAGER_ACTION_CUSTDELETE_ERR_INVALID'      => 'keine gültige Einstellung gesetzt',
    'D3_USERMANAGER_ACTION_CUSTDELETE_DESC'             => 'Beachten Sie, dass diese Anpassung nicht rückgängig gemacht werden kann.',
    'D3_USERMANAGER_ACTION_USERADDFIELDVALUE'           => 'Kundenfeld mit Wert füllen',
    'D3_USERMANAGER_ACTION_USERADDFIELDVALUE_FIELD'     => 'Feldname',
    'D3_USERMANAGER_ACTION_USERADDFIELDVALUE_FIELD_DESC'=> 'Diese Aktion befüllt ein frei definierbares Feld der "oxuser"-Datenbanktabelle. Tragen Sie hier den tatsächlichen Namen des zu befüllenden Feldes ein. Soll Inhalt in Sprachfeldern (*_1) eingefügt werden, ist hier die Angabe des Multilang-Namens erforderlich.',
    'D3_USERMANAGER_ACTION_USERADDFIELDVALUE_VALUE'     => 'Feldwert',
    'D3_USERMANAGER_ACTION_USERADDFIELDVALUE_DESC'      => 'Geben Sie den endgültigen Inhalt an, der in das definierte Datenbankfeld eingefügt wird. Die Verwendung von Variablen, Platzhaltern und referenzierenden Feldnamen ist hier nicht möglich.',
    'D3_USERMANAGER_ACTION_USERADDFIELDVALUE_ERR_FIELD' => 'kein gültiges Feld gewählt',
    'D3_USERMANAGER_ACTION_USERADDFIELDVALUE_ERR_VALUE' => 'kein gültige Wert definiert',
    'D3_USERMANAGER_ACTION_USEREXECUTEMETHOD'           => 'Methode des Kundenobjekts ausführen',
    'D3_USERMANAGER_ACTION_USEREXECUTEMETHOD_NAME'      => 'Methodenname',
    'D3_USERMANAGER_ACTION_USEREXECUTEMETHOD_DESC'      => '<p>Geben Sie hier ausschließlich den Namen der Methode an. Parameter oder Klammern dürfen nicht verwendet werden.</p><p>Die Methode muss "public" am Benutzerobjekt ("oxuser" und deren Erweiterungen) existieren. Der Methodenaufruf erfolgt <b>nicht</b> statisch.</p><p>Diese Parameter werden der Methode übergeben: <ul><li>aktuell verwendetes Kundenmanagerauftragsobjekt ("d3usermanager" bzw. dessen Überladung)</li></ul></p><p>Als Rückgabewert wird ein boolean erwartet, der definiert, ob das Benutzerobjekt gespeichert werden muss.</p>',
    'D3_USERMANAGER_ACTION_USEREXECUTEMETHOD_ERR_INVALID'      => 'keine gültige Methode gesetzt',
    'D3_USERMANAGER_ACTION_EXPORTGROUP'                 => 'Export',
    'D3_USERMANAGER_ACTION_EXPORT'                      => 'Kunden in Liste exportieren',
    'D3_USERMANAGER_ACTION_EXPORTCONTAINS'              => 'enthaltene Felder: ',
    'D3_USERMANAGER_ACTION_EXPORTLOCATION'              => 'Export wird abgelegt unter: ',
    'D3_USERMANAGER_ACTION_EXPORTTEMPLATE'              => 'Generierungstemplate: ',
    'D3_USERMANAGER_ACTION_EXPORTTEMPLATE_DESC'         => 'Geben Sie hier den Namen des Templates an, welches die Struktur des Exports enthält (Bsp.: "CSV-Vorlage.tpl"). Liegt das Template in einem Unterverzeichnis des unten genannten Ordners, fügen Sie die erweiternden Pfadangaben hinzu (Bsp.: "d3usermanager/CSV-Vorlage.tpl"). <br><br>Beipiele für Exportvorlagen finden Sie im Modulpaket unter "application/view/admin/tpl/d3usermanager". Legen Sie für eigene Formate ein entsprechendes Template an.',
    'D3_USERMANAGER_ACTION_EXPORTEXTENSION'             => 'Dateiendung der Exportdatei: ',
    'D3_USERMANAGER_ACTION_EXPORT_ERR_INVALIDFIELD'     => 'keine gültigen Felder ausgewählt',
    'D3_USERMANAGER_ACTION_EXPORT_ERR_INVALIDTPL'       => 'kein gültiges Exporttemplate definiert',
    'D3_USERMANAGER_ACTION_DATEPLACEHOLDER'             => '[Datum]',
    'D3_USERMANAGER_ACTION_EXPORTEXTENSION_DESC'        => 'Hier können Sie die Dateiendung der zu exportierenden Datei angeben. Dies sind z.B. für CSV-Dateien die Endung "csv" oder "txt". XML-Dateien haben in der Regel die Endung "xml". Beachten Sie bitte: Für den Inhalt der Exportdateien ist nicht die Dateinamenendung verantwortlich. Dieser muss die passende Exportvorlage zugeordnet sein.',
    'D3_USERMANAGER_ACTION_USERSENDPUSHNOTIFICATION'    => 'Push-Benachrichtigung senden',
    'D3_USERMANAGER_ACTION_USERSENDPUSHNOTIFICATION_URL' => 'Dienst-URL',
    'D3_USERMANAGER_ACTION_USERSENDPUSHNOTIFICATION_METHOD' => 'Übertragungsmethode',
    'D3_USERMANAGER_ACTION_USERSENDPUSHNOTIFICATION_DESC' => '<p>Geben Sie hier die URL des Dienstes oder Scriptes an, der die Nachricht empfangen soll und wählen Sie die bevorzuge Übertragungsmethode (POST ist für die Fälle Standard).</p>',
    'D3_USERMANAGER_ACTION_USERSENDPUSHNOTIFICATION_ERR_INVALIDMETHOD' => 'keine gültige Übertragungsmethode gewählt',
    'D3_USERMANAGER_ACTION_USERSENDPUSHNOTIFICATION_ERR_INVALID' => 'keine gültige Einstellung gesetzt',

    'D3_USERMANAGER_ACTION_DELETE'                     => 'Löschen',
    'D3_USERMANAGER_ACTION_INFO'                       => 'Informationen',
    'D3_USERMANAGER_ACTION_MAILSEND'                   => 'E-Mail senden',
    'D3_USERMANAGER_ACTION_MAILSEND_FROM1'             => '',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMSUBJECT'       => 'Betreff-Template',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMCMS_SUBJECT'   => 'Der CMS-Titel ist gleichzeitig der Mail-Betreff.',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMTEMPLATE'      => 'aus Templatedatei',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMTEMPLATE_HTML' => 'HTML-Template',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMTEMPLATE_PLAIN'=> 'Plain-Template',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMTPL_ADMIN'     => 'aus <b>Admin</b>-Templateverzeichnis',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMTPL_FRONTEND'  => 'aus <b>Frontent</b>-Templateverzeichnis',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMTPL_MODULE'    => 'aus <b>Modul</b>-Verzeichnis',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMTPL_DESC'      => 'Neben den Templates werden auch die Sprachbausteine je nach Einstellung immer aus dem Admin- bzw. Frontend-Bereich übersetzt. Übertragen Sie daher ggf. die Einträge manuell. Laden Sie ein Template aus einem Modulverzeichnis, werden generell die Frontend-Sprachbausteine verwendet.',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMTEMPLATE_DESC' => 'Geben Sie den vollständigen Templatenamen (inkl. Ordner ab tpl-Ordner und Dateiendung) an',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMCMS'           => 'aus Kundeninformation',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMCMS_HTML'      => 'HTML-CMS',
    'D3_USERMANAGER_ACTION_MAILSEND_FROMCMS_PLAIN'     => 'Plain-CMS',
    'D3_USERMANAGER_ACTION_MAILSEND_FROM2'             => 'an',
    'D3_USERMANAGER_ACTION_MAILSEND_TOCUSTOMER'        => 'Kunde',
    'D3_USERMANAGER_ACTION_MAILSEND_TOOWNER'           => 'Shopbetreiber',
    'D3_USERMANAGER_ACTION_MAILSEND_TOMAIL'            => 'folgende Mailadresse(n)',
    'D3_USERMANAGER_ACTION_MAILSEND_TOMAIL_DESC'       => 'Geben Sie in dem Eingabefeld eine oder mehrere gültige Mailadressen (mit Semikolon getrennt) an und aktivieren Sie die Option mit dem Häkchenfeld.',
    'D3_USERMANAGER_ACTION_MAILSEND_USEALTREPLYADR'    => 'spezielle Absende- und Reply-Adresse',
    'D3_USERMANAGER_ACTION_MAILSEND_USEALTREPLYADR_DESC'=> 'Geben Sie hier bei Bedarf eine spezielle Absendeadresse an. Diese wird dann ebenfalls als Reply-Adresse verwendet. Ohne Angabe wird die Absendeadresse des Shops verwendet. Kontrollieren Sie bitte, dass diese Mailadresse auch von Ihrem SMTP-Server verwendet werden darf.',
    'D3_userMANAGER_ACTION_MAILSEND_ERR_NOVALIDSOURCE' => 'keine gültige Inhaltsquelle gesetzt',
    'D3_USERMANAGER_ACTION_MAILSEND_ERR_NOVALIDTPL'    => 'kein gültiges Template gesetzt',
    'D3_USERMANAGER_ACTION_MAILSEND_ERR_NOVALIDCMS'    => 'kein gültiger Textbaustein gewählt',
    'D3_USERMANAGER_ACTION_MAILSEND_ERR_NOVALIDRCP'    => 'kein gültiger Empfänger definiert',
    'D3_USERMANAGER_ACTION_INDIV'                      => 'Individualaktionen',
    'D3_USERMANAGER_ACTION_MARKASFINISHED'             => "gefundene Kundenkonten als erledigt markieren",
    'D3_USERMANAGER_ACTION_MARKASFINISHED_MESSAGE'     => '%1$u von %2$u Kundenkonten/-konto wurde(n) als erledigt markiert',

    'D3_USERMANAGER_STAT'                              => 'Kundenmanager - Statistik',
    'D3_USERMANAGER_STAT_FINISHED'                     => 'Anzahl bisher bearbeiteter Kundenkonten:',
    'D3_USERMANAGER_STAT_FINISHED_DESC'                => 'Diese Anzahl Kundenkonten wurden insgesamt von diesem Auftrag bearbeitet. Ob sich zwischenzeitlich die Bedingungen änderten, ist hierfür unrelevant.',
    'D3_USERMANAGER_STAT_FINISHEDMONTH'                => 'Anzahl im letzten Monat bearbeiteter Kundenkonten:',
    'D3_USERMANAGER_STAT_FINISHEDMONTH_DESC'           => 'Diese Anzahl Kundenkonten wurden im letzten Monat von diesem Auftrag bearbeitet. Ob sich zwischenzeitlich die Bedingungen änderten, ist hierfür unrelevant.',
    'D3_USERMANAGER_STAT_TOFINISHED'                   => 'Anzahl noch zu bearbeitender Kundenkonten:',
    'D3_USERMANAGER_STAT_TOFINISHED_DESC'              => 'Nach den aktuell eingestellten Bedingungen (mit Ausnahme der Individualbedingungen) ist diese Anzahl Kundenkonten für diesen Auftrag relevant. Würde der Auftrag aktuell gestartet werden, würden diese Kundenkonten bearbeitet. Die Individualbedingungen können bei dieser Auswertung aus technischen Gründen nicht berücksichtigt werden.',
    'D3_USERMANAGER_STAT_NOTFINISHED'                  => 'Anzahl bisher nicht bearbeiteter Kundenkonten:',
    'D3_USERMANAGER_STAT_NOTFINISHED_DESC'             => 'Diese Anzahl Kundenkonten wurden bislang von diesem Auftrag nicht bearbeitet. Möglicherweise entsprachen diese Kundenkonten nicht den Bedingungen oder die Bearbeitung wurde noch nicht gestartet.',

    'D3_USERMANAGER_USERMAIN_USERMANAGER'            => 'Kundenmanager',
    'D3_USERMANAGER_USERMAIN_NOUMJOBS'                => 'keine manuell ausführbaren Aufträge vorhanden',
    'D3_USERMANAGER_USERMAIN_EXECON'                  => 'ausgef. am',
    'D3_USERMANAGER_USERMAIN_EXECSTART'               => 'für dieses Kundenkonto ausführen*',
    'D3_USERMANAGER_USERMAIN_REEXECSTART'             => 'erneut für dieses Kundenkonto ausführen*',
    'D3_USERMANAGER_USERMAIN_CHANGEEXEC'              => 'Mails anpassen und Auftrag ausführen*',
    'D3_USERMANAGER_USERMAIN_SAVEEXEC'                => 'Auftrag mit diesem Inhalt ausführen*',
    'D3_USERMANAGER_USERMAIN_EXECINCLALLACTIONS'      => '* inkl. aller anderen konfigurierten Aktionen dieses Auftrags',
    'D3_USERMANAGER_USERMAIN_CANCELEXEC'              => 'Auftrag abbrechen',
    'D3_USERMANAGER_USERMAIN_NOCHANGEEXEC'            => 'keine Anpassungen bei diesem Auftrag möglich',
    'D3_USERMANAGER_USERMAIN_EXECRESET'               => 'für erneute Ausführung zurücksetzen',
    'D3_USERMANAGER_USERMAIN_EXECRESETCONFIRM'        => 'Soll der Auftragsstatus wirklich zurückgesetzt werden?',
    'D3_USERMANAGER_USERMAIN_EXECSTART_DESC'          => '* ohne Verwendung der Bedingungen',
    'D3_USERMANAGER_USERMAIN_RECIPIENT'               => 'Empfänger:',
    'D3_USERMANAGER_USERMAIN_SUBJECT'                 => 'Betreff:',
    'D3_USERMANAGER_USERMAIN_HTML'                    => 'HTML:',
    'D3_USERMANAGER_USERMAIN_GENPLAIN'                => 'Plain (unformatiert) aus formatiertem Text erstellen',
    'D3_USERMANAGER_USERMAIN_GENPLAIN_DESC'           => 'Hierbei werden Zeilenumbrüche umgestellt und alle HTML-Tags entfernt. Je nach verwendeter Formatierung kann dies zu unpassender Darstellung führen. Tragen Sie dann besser den Plaintext selbst ein.',
    'D3_USERMANAGER_USERMAIN_PLAIN'                   => 'Plain:',

    'D3_USERMANAGER_MAIL_UMJFROM'                     => 'Kundenmanager - Auswertung von',
    'D3_USERMANAGER_MAIL_USER'                        => 'Kundenkonto:',
    'D3_USERMANAGER_MAIL_GENERAL'                     => 'Allgemein:',
    'D3_USERMANAGER_MAIL_USERFROM'                    => 'vom',
    'D3_USERMANAGER_MAIL_USERNAME'                    => '',
    'D3_USERMANAGER_MAIL_USERSUBJECT'                 => 'Kundenmanager Ausführungsstatus',

    'D3_USERMANAGER_JOBDESC_SETACTIVEFLAG'             => 'als "%s" markieren',
    'D3_USERMANAGER_JOBDESC_ADDCUSTGROUP'              => 'füge Kunde zu Gruppe "%s" hinzu',
    'D3_USERMANAGER_JOBDESC_REMOVECUSTGROUP'           => 'entferne Kunde aus Gruppe "%s"',
    'D3_USERMANAGER_JOBDESC_DELETE'                    => 'gelöscht, weitere Bearbeitung abgebrochen!',
    'D3_USERMANAGER_JOBDESC_SETFIELDVALUE'             => '"%s" in Feld "%s" gesetzt',
    'D3_USERMANAGER_JOBDESC_EXECUTEMETHOD'             => 'oxuser-Methode "%s" ausführen',
    'D3_USERMANAGER_JOBDESC_EXPORTLIST'                => 'exportiere in Liste %s',
    'D3_USERMANAGER_JOBDESC_SENDMAIL'                  => 'sende E-Mail an %s',
    'D3_USERMANAGER_JOBDESC_ADDREMARK'                 => 'füge Remark hinzu',

    'D3_USERMANAGER_JOBERR_NOGROUP'                    => 'FEHLER: Kundengruppe ist nicht vorhanden: %s',
    'D3_USERMANAGER_JOBERR_NOGROUPDEFINED'             => 'FEHLER: Keine Kundengruppe gewählt',
    'D3_USERMANAGER_JOBERR_NOTEXECUTABLE'              => 'Die Aktion kann nicht ausgeführt werden, da möglicherweise Lizenzeinschränkungen greifen oder benötigte Parameter nicht vollständig oder fehlerhaft gesetzt sind',

    'D3_USERMANAGER_CONFIGVARS_IEXECJOBSLIMIT'         => 'Anzahl ausführbarer Aufgaben:',
    'D3_USERMANAGER_CONFIGVARS_SADDTITLE'              => 'Modul-Edition:',
    'D3_USERMANAGER_CONFIGVARS_BLUSEMAILSENDONLY'      => 'beschränkt auf Mail-Sende-Aktionen:',

    'D3_USERMANAGER_REMARK_NOTE'                       => '[Userm.]',

    'D3_USERMANAGER_ERROR_IEXECJOBSLIMIT'              => 'Ihre Modullizenz erlaubt Ihnen eine maximale Anzahl an Aufgaben. Sie können weitere Aufgaben anlegen, diese werden jedoch nicht ausgeführt. Lassen Sie Ihre Lizenz dafür erweitern.',
    'D3_USERMANAGER_ERROR_RESTRICTIONS'                => 'Sie nutzen die "%s"-Edition. Möchten Sie die inaktiven Funktion nutzen, lassen Sie Ihre Lizenz dafür erweitern.',
    'D3_USERMANAGER_ERROR_NOMALL'                      => 'Mandanten stehen in Ihrer Shopedition nicht zur Verfügung.',
    'D3_USERMANAGER_ERROR_MISSINGREQUACTIONVALUES'     => 'Die markierten Aktionen erfordern zusätzliche Einstellung zur fehlerfreien Ausführung. Bitte kontrollieren Sie Ihre Angaben.',
    'D3_USERMANAGER_ERROR_MISSINGREQUREQUIREMENTVALUES'=> 'Die markierten Bedingungen erfordern zusätzliche Einstellung zur fehlerfreien Ausführung. Bitte kontrollieren Sie Ihre Angaben.',

    'D3_USERMANAGER_FIELDTITLE_OXID'                   => 'Kunden-Ident',
    'D3_USERMANAGER_FIELDTITLE_OXACTIVE'               => 'Aktivstatus',
    'D3_USERMANAGER_FIELDTITLE_OXRIGHTS'               => 'Kontotyp',
    'D3_USERMANAGER_FIELDTITLE_OXSHOPID'               => 'Shopzuordnung',
    'D3_USERMANAGER_FIELDTITLE_OXUSERNAME'             => 'E-Mail',
    'D3_USERMANAGER_FIELDTITLE_OXPASSWORD'             => 'Passwort',
    'D3_USERMANAGER_FIELDTITLE_OXPASSSALT'             => 'PW-Codierung',
    'D3_USERMANAGER_FIELDTITLE_OXCUSTNR'               => 'Kundennummer',
    'D3_USERMANAGER_FIELDTITLE_OXUSTID'                => 'USt-ID-Nr.',
    'D3_USERMANAGER_FIELDTITLE_OXCOMPANY'              => 'Firma',
    'D3_USERMANAGER_FIELDTITLE_OXFNAME'                => 'Vorname',
    'D3_USERMANAGER_FIELDTITLE_OXLNAME'                => 'Nachname',
    'D3_USERMANAGER_FIELDTITLE_OXSTREET'               => 'Straße',
    'D3_USERMANAGER_FIELDTITLE_OXSTREETNR'             => 'Hausnummer',
    'D3_USERMANAGER_FIELDTITLE_OXADDINFO'              => 'zus. Infos',
    'D3_USERMANAGER_FIELDTITLE_OXCITY'                 => 'Stadt',
    'D3_USERMANAGER_FIELDTITLE_OXCOUNTRYID'            => 'Land-ID',
    'D3_USERMANAGER_FIELDTITLE_OXSTATEID'              => 'Bundesland-ID',
    'D3_USERMANAGER_FIELDTITLE_OXZIP'                  => 'Postleitzahl',
    'D3_USERMANAGER_FIELDTITLE_OXFON'                  => 'Telefonnummer',
    'D3_USERMANAGER_FIELDTITLE_OXFAX'                  => 'Telefaxnummer',
    'D3_USERMANAGER_FIELDTITLE_OXSAL'                  => 'Anrede',
    'D3_USERMANAGER_FIELDTITLE_OXBONI'                 => 'Bonität',
    'D3_USERMANAGER_FIELDTITLE_OXCREATE'               => 'Erstelldatum',
    'D3_USERMANAGER_FIELDTITLE_OXREGISTER'             => 'Registrierdatum',
    'D3_USERMANAGER_FIELDTITLE_OXPRIVFON'              => 'priv. Tel.-Nummer',
    'D3_USERMANAGER_FIELDTITLE_OXMOBFON'               => 'Mobiltel.-Nummer',
    'D3_USERMANAGER_FIELDTITLE_OXBIRTHDATE'            => 'Geburtsdatum',
    'D3_USERMANAGER_FIELDTITLE_OXURL'                  => 'Internetadresse',
    'D3_USERMANAGER_FIELDTITLE_OXDISABLEAUTOGRP'       => 'nur man. Gruppenzuordn.',
    'D3_USERMANAGER_FIELDTITLE_OXUPDATEKEY'            => 'ID zur PW-Erneuerung',
    'D3_USERMANAGER_FIELDTITLE_OXUPDATEEXP'            => 'Ablauf für PW-Erneuerung',
    'D3_USERMANAGER_FIELDTITLE_OXPOINTS'               => 'Bonuspunktestand',
    'D3_USERMANAGER_FIELDTITLE_OXFBID'                 => 'Facebook-ID',
    'D3_USERMANAGER_FIELDTITLE_OXTIMESTAMP'            => 'Datum letzte Änderung',

    'D3_USERMANAGER_FIELDADD_LANG'                     => ' - Sprache %u',
    'D3_USERMANAGER_FIELDDESC'                         => '%1$s (%2$s)',

    'D3_USERMANAGER_EXC_DBFIELDNOTFOUND'               => 'Das angegebene Datenbankfeld "%2$s" existiert nicht in der Tabelle "%1$s".',
    'D3_USERMANAGER_EXC_METHODNOTFOUND'                => 'Die angegebene Methode "%2$s" existiert nicht im %1$s-Objekt.',

    'D3USERMANAGER_CONFIGVARS_SEDITIONID'              => 'Editions-ID',

    'D3_USERMANAGER_GENERAL_TASK'                      => 'Aufgabe:',

    'D3_USERMANAGER_CLI_COMMON_UNVALIDSHOPID'           => 'ungültige Shop-ID',
    'D3_USERMANAGER_CLI_COMMON_UNVALIDCJID'             => 'ungültige Cronjob-ID',
    'D3_USERMANAGER_CLI_HELP'                           => 'Ermöglicht die Ausführung von Kundenmanageraufgaben.',
    'D3_USERMANAGER_CLI_OPTION_VERSION'                 => 'zeigt Version',
    'D3_USERMANAGER_CLI_OPTION_QUIET'                   => 'verhindert die Anzeige der Ausgabe',
    'D3_USERMANAGER_CLI_OPTION_LANG'                    => 'optional - Sprache der ausgegebenen Meldungen, mögliche Werte sind: "%1$s"',
    'D3_USERMANAGER_CLI_OPTION_HELP'                    => 'Diesen Hilfetext anzeigen und den Aufruf verlassen.',
    'D3_USERMANAGER_CLI_OPTION_NOCOLORS'                => 'Verwendet keine Farben in der Ausgabe. Nützlich bei der Weitergabe der Ausgabe an andere Tools oder Dateien.',
    'D3_USERMANAGER_CLI_OPTION_LOGLEVELS'               => 'Kleinstes Level der anzuzeigenden Meldungen. Standard ist "info". Gültige Stufen sind: "debug", "info", "notice", "success", "warning", "error", "critical", "alert", "emergency".',
    'D3_USERMANAGER_CLI_COMMAND'                        => 'Dieses Tool akzeptiert einen Befehl als ersten Parameter, wie unten beschrieben:',
    'D3_USERMANAGER_CLI_COMMAND_RUN'                    => 'Ausführen der Aufgabengruppe mit definierter Cronjob-ID',
    'D3_USERMANAGER_CLI_COMMAND_STATUS'                 => 'Statusinfos zur Cronjob-ID anzeigen',
    'D3_USERMANAGER_CLI_ARGUMENT_CJID'                  => 'ID der zu startenden Aufgabengruppe (kann im Shop-Backend eingestellt werden), mögliche Werte sind: "%1$s"',
    'D3_USERMANAGER_CLI_ARGUMENT_SHOPID'                => 'ID des ausgewählten Shops, mögliche Werte sind: "%1$s"',
    'D3_USERMANAGER_CLI_ARGUMENT_KEY'                   => 'optional - nur für externe Anrufe erforderlich,'.PHP_EOL.'Zugriffsschlüssel zur Verhinderung externer unbefugter Anrufe (kann im Shop-Backend eingestellt werden)',
    'D3_USERMANAGER_CLI_ARGUMENT_ENCLOSER'              => '", "',
    'D3_USERMANAGER_CLI_FINISHED_SUCCFESSFULLY'         => 'Die Scriptausführung wurde beendet.',
    'D3_USERMANAGER_CLI_FINISHED_ERRORS'                => 'Diese Fehler sind aufgetreten:',
    'D3_USERMANAGER_CLI_DEPRECATED'                     => 'Die Cronjobausführung über dieses Script wird mittelfristig deaktiviert. Bitte stellen Sie den Cronjob auf diesen Konsolenaufruf um: "./vendor/bin/d3_usermanager_cron" um.',

    'D3_USERMANAGER_SETUP_CRONPASSWORD'                 => 'Für die Absicherung externer Cronjobaufrufe wird ein sicheres Passwort gesetzt. Dieses können Sie später in den Moduleinstellungen einsehen und bei Bedarf verändern.',
    
    'D3_USERMANAGER_EXC_CRON_MODULEDISABLED'            => 'Kundenmanagermodul ist deaktiviert.',
    'D3_USERMANAGER_EXC_CRON_UNAVAILABLE'               => 'Cronjob Aufruf ist deaktiviert.',
    'D3_USERMANAGER_EXC_CRON_WRONGPASSWORD'             => 'Fehlendes oder falsches Cronjobpasswort.',
    'D3_USERMANAGER_EXC_ACTION'                         => 'Aufgabe "%1$s" -> Aktion "%2$s": %3$s',
    'D3_USERMANAGER_EXC_REQU'                           => 'Aufgabe "%1$s" -> Bedingung "%2$s": %3$s',
);

// @codeCoverageIgnoreEnd
