# This Software is the property of Data Development and is protected
# by copyright law - it is NOT Freeware.
#
# Any unauthorized use of this software without a valid license
# is a violation of the license agreement and will be prosecuted by
# civil and criminal law.
#
# https://www.d3data.de
#
# @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
# @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
# @link      https://www.oxidmodule.com

parameters:
  Html2Text\Html2Text.args.html:

services:
  Html2Text\Html2Text:
    class:      Html2Text\Html2Text
    shared:     false
    arguments:
      - '%Html2Text\Html2Text.args.html%'

  d3.usermanager.D3\OxidSqlLogger\OxidEsalesDatabase:
    class:      D3\OxidSqlLogger\OxidEsalesDatabase
    shared:     false

  ReflectionClass:
    class:      ReflectionClass
    shared:     false
    arguments:
      - '@ReflectionClass.args.object'
