<?php //006ed
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Kundenmanager @version 4.1.2.0 PHP71 (15.03.2021) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2021, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPnolrATQTos88nj1XFyl3m7p3HtQXaVgD+vZgvCiWXzOtsbCOY2oSEiGZisZWGv6ikEdyPke
VV/ViSVm+0p//quoBSjvx3Kzstnd0z4IFlUPk0rEBxtDkWAVyT7qKLT6O/EShIGYDjIKo5ORAt46
A0OFMgO8V9ytab6spsl9irIKsutA5m5VdMGFH9X+hkkRfgGzC9h83CTTYBObbKKAenvMpJ4AZAgd
waENMtmmTHlEvwOMbHJlALMPOqNJdqdthy92pAsWswmstzH76/YApXuuDS6CPsQa86o9y4gG4bEt
PZ6aFaVVKGzfXELMiUP9fElN8D2li9yQGujn/97sr8xWY7Zi1Pa61ogPXbxKgDjRsCxK25yWTYQ/
xDLLvBsRVKXQ9H8iGPlFFnpQSvvC99OM13LC9Ws7LaZMx/66oxCDU2/QlodgiOKcgq+TkEI5C8N0
dBkfvzoJQMlYYLRM/eDha5shlAuu7myJnXsyXY6F0BL5DP7IZmqWGlnn8FMMXJ1UIHByliDxZ+VE
cxeYv6xtHFtD5NgYISXIHmQkqTcfyK8j6XHLbP9UGeiqqhavcJR97Kau1o5K2QlpoxRak/EGSFIQ
yr6uLNCkSG==