<?php //006f9
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Kundenmanager @version 5.1.3.0 PHP73 (07.09.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPoOjbgvxysg10fy3ZTtoS1T3sh4vwYwwzjjREAebU3sDe5OGvlk8z/J4C4DNUDgW+4ycYeja
P3uQz6OnLP6aIH4Mxi5jN4n3WXYzJZUusiVdZqnvk8IDoZTCdevwaMukrDhUTPTteMx/VXF/PLPA
jNIBijG/BPDSeTHuTYfQTxtpeoyaaTctmK02dG6jLE09PXZRH7qumZvpzdvmAQmAZriiKnu3ZvyX
NLkTG9OIp9BXrF4/Wpw6X1XRg8TVz59f3nZ40hnSv9W+eYjeTDvPqavj/33YPfg0VG2icmoEnjg/
Uh2eB/+vJcNGu4XrXAnWDt+dwx12UVsOmJkO/e1Fi9zPTyNNYzz4a62dd21aTeUCDHKLlwIss+bj
NJFUUzoHwPNj/4wwgdK2boo9/mCBE88DhU2zj/j9GxFmAQra0tifXVulVw+jb43q10vHMCeqRFMh
qnc4iGY6Amg/Pzeig3j+vZ6uQQVJpaLlwz1BOyd/gMwhqTUEi1dxbOq/5LFKkD2LGhigdvD0/OmK
dfhQzA6Vn06GzAsviIT8OAEoTFDRQ5jaWzYLLVyCAnfQVAg9jQmwz4ciPmjWB5s9bM73fBLKzAu+
9SRy9Fx+EHXgbC31OFj+geuiVfyQZDrkSIGawSCwad5v9G0Mcvm1XbGjCrnj4ZKJoMvDLES8Bdrv
/osYfU9s1FRwwdrgHRMPCH9qw3U68T6w+Qqd3SNgpNDX8+wGgWBWCS7UgHsGb2Zqte/kflJwbQ2G
n9Zsl8AGih+S/KnCW+Hly6lrkuSeb2nMQsoNES9dNIjx2VB+uMnBT3bEztfCnHuhoa8sgkhu4WDD
ox1u80GMN8gGV4YMIRcvzzD6lcEI4crayiDwk4CSmXQgNYek4uuoxvIskqDZH2JOq+iOJ4tsIosg
b0j3RIYOuzm5BQroXSkzo0JL52eRM7JiOTw+TdKFdt+c1c2B136Bp0Wm3BTKiCUUfxyRx+5/NwFQ
eDOn3pIA9ZJ9R7fS9ahgtUEspLEe3vw834JfH14hdn/2Rv0WTAHlAst850ZIxklq5DFbVBxi2z7m
nNigHYhigO8oum5Sd9BAfRO6mKmPmMAgWQsDek6NvFccrdXOh0bb4G1mqGeVT5QQSp2Y6aIGRiEE
XKiYCd0M2L4U1EhSvbIIQdvxdRlLHffpPfL3pmM+d//CtFDA64c8c8zFVCq710XJhPFW+naMvoBq
+vxAIc5y9vn5h/LGGHAWozBO9aAugcZUOy+WYGe+L4NWUDIlnN0o+gezuxRwm3lOV/bz0ytZ8Mqr
fGt+YfwQEFBaikFb4xMAyHW1sYnqEtM/xcZ+JsN7TwJLy5P0xlYTGUlpO73bp/5oJyDg6S/vefzH
q4uK3KsSC2UNtJ4fXJDcbieE3fftuV+GzOSEUmWi9yTOUcL7JlWoVSs2iDp8B1TEfkLrJxUXBarY
zHXtxEoPjbkcRwdnbwDsSEHeR8arr83oNfvFvwSHHn2WbYXTGdiZNzlUW9j8ZbCjK79qdo5PIr7W
6QiI5DMLsSTY6oC3ggIuCaNpgHARQiS9KUPxEEW1+2jGQD2bs39eM/ub26mCHBiaCOO7euASRh0M
/C0F0wGVVW8khyPsb4QEZBEaNCUD0pbDZsOCOnQOe5OnnSJurz/OobFz7f4Inj63ftoZsYE2VKUx
ZdnOSW0wwrr+LUEFKy+wGCeJ6uCMrsd5bcDgdsHXjZ9m02c7uNTJ2aDN5DnO7vDI3EFuvl53/Ggg
TmbSSW4HatAUM+UsyLOacG1ZQgteYIlKtSNQS0FJcxPKomZ9KjJLiQIxvP7jZLSewA6TgqrKh2Xx
DRlUzt2aSM02uf9+d2O3CcG0DG2BCTtuNGsHUOdBqR0EBVwBYA+L7L6WMNq1zhhlPhsw7TywmjeG
unqbCH1UfXL6jVSqSPvRUjxREs52ox5d/NCdwtwBLlRfT6oRo/QJHbb1uq8YeIISy2M7v3TH8Uec
vq1UQyCDrgwiU9eMkxej1UrjMV0ogjmMRo246mowJZRQtpH94m/06gLvdQ2L2KEQ7Y8KU9XBnUXv
z8MVlILZ0hNPwQo6zK62DK3gcNhlzoZoNiM+AaujPGmfSauTWF8sqFOUhmYfmD/ijajVvuksqzU8
wufHKgap6+hy1mxyHChywrTtn1mLIJMU2jHUCD2tNsjzeZUmGatj0kpfVtIbxuvKHJkxwp0DTuxg
T9vm+qPEBmf/lFJCQ8Qv95PNH3dvPmQd5sMZuoH0wDHzItCu7NimM3dFC13xNT/6qSbYRQ3g/hRP
b3w0RUM7DN+rhX70quRxtY+YY7InbnxVs43cSO19nhubKL4W2HBM3z5wx4WDoLd8Z5106L/VuFxF
hoLn0rx83fT10UHIjidtf9oGKY0w3rYgBrCeMKfF9Qvj0LvvHTc0+ALdC6ILBXFdpGa3rMa5RKqE
LInVbXo5dgFgcz2Vk0uNcBNhJwT57wJufzXXv03L1Phqi2eLemKmD5oim6SgCSy820wvOO/HFN/J
w6Vq6pt+5mEv2awkoO+IxNc4jaeRNN0vaRIs8u6rpeS7EZYo7VF77s72cTlZsz/zxp96pZJoivJL
1r7rtQF+SokuvVvoq+wbEJ8oPSyAsAw6wpGngLeoahuVId9BhIwbj9EETNfBgpSR4Iqhh2KkRxTp
VJWLYZVFW6Umge1elL9uIn0=