<?php //006f9
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Kundenmanager @version 5.1.1.3 PHP73 (03.05.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPvxifWgjIXijg5WpAUBQ90Qxc86NonCElxYuWlHfp4dHvNoxk2eP38/RhLtnTsOLy/tnmC9u
O4uEmexpLCMEAt7NWKBdbOneP8yALN6kmQNRwyBNe+Nxv2Kjp7FHo71QAtV0dduxW7dTRq/MSm/w
dD2xunN2kFBIFojPA0/QUaKKCcsO0grERYHIUtpBhMTCWNrBu/mz8ipzRX4Quidk2sLMr0jpS7qa
qcYtSjEeFpE2MbP7ARr23jISg5gmErc6YH8qR0Vf1kk2KfvYPTXIkqyb3STfCcmoLRPIheADo9b4
jOWQtI3oe3adIBxyJGYZiMbBXFKJja7xUg4tqvkJr+ATOPhPiBcMMPTndfg+1u7hHB8K+67cYT8h
l4o2aJr9kThfHJgxgYC+y3guadjGQq+Kqai2eIUwxRkRWtkq0rZxX+BbPQP9LySDxVuSEZiic/cw
z+X0D0Vy3LQXcpisRNrV8qI4+8gmbpKsakiPw0g6RThRUIVf8LuXdnJMrCtgRF0zBA/PE4hGqQTx
+xha+YkVVodeMFc/EOFAN98CfSdrIQMgykeljLetJxXSPWY1g9tNsuNFWcpaXwcX9rOk9EsjkjXs
rfW=