<?php //006f9
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Kundenmanager @version 5.1.1.1 PHP73 (16.03.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPn7YhLmtJHQJpb4uVuMm5RPg4dgPCtbfuVzOOobNa8pGBV5RbqWvKWSt0twDu9V2TqCEC7A7
zeStFYVE64RZz1w8knC6Xu1RDFxX7KtG2NFpQkauD82gpjMLzqaA4NyuWfCENWHexdrtWxHcAE68
NvhXXE0c95ISJKW7lFnrfv2J9/sxdQTibBhlGd+bE6KJlWI68yH+KUpn++63EBk4Dwj5XgMBZKOr
voHwW1/XSx0d/oigZ0UIIchRdn0llDTbLXOvTBFDuy6a6ElEC8Ad73TVhsRmQcKG1yiA7WHR0Hf8
Qyl8fnh/PyvbqPVGVd+B0xUIdOFdxDNcEVaLoJzOoxokJxRyScOe/GfCWDZ8TbAEudD87eq1NKY1
8b0o1BHVWcLv30z6nvGrylebGc7vGalUIs04YckYFNOkv+tyR0FMmtfJUjV07JJHhQ9xrpOFZpkE
tomu+XWbah1kTZt2T244eCNPdG/YnScZincByLWx5GFQ/dgxiqCX/Buax/DURQzdrBxffibLXii8
QfChSNvqqjGkQc9GxNwDsMLro6Z7b+TtukgNtp4eWLj/EglL1Elv2+Y5LW1fZAxH6pyOhFRjGgd2
NuKLiw7eccxF1dSx+kvRpkWK///Kz7nuc7FYC2pdI05oUuNfguIfbXX67pAfV7iDbCjlmjrydlkW
SpTMLr/9hDVJAxoPVhx9ZBQnn5dvExpXH961vUcZQHPXKZRfEQUpmLV8EB1HTOLBrLLmRUWu3gDd
zBYrlY4/S9CcsFOIb5Ne1g6xnCUmgcp3uXoFw9H03lVtgxQgbm8F1xfNuGvrQKUrXf0JkMa4c+GG
UKTfWwYATteprXyzJ43m4Z1PwPx/cWNBBmCnethgpw5kCml3QXU1fo041LLHMUk6dlOHs9vb1y9a
FpcBwazaaLEmv+F/HQXvDdsoR0RdmOXeWLRVQ0z2eGweh/pMTMcGkzwOI80jJiGMH8mPOE8jc7uU
EuKb4T8VcuH4ZPkruNrSDtjkcGf9IHqmYw0UIz08Tr8HWfMZO3AFsVMeEwsP63rn0mXB/irifQZw
heTxpkJEg3u3aRKl+8y60QCk3/+69MG+wqMkMyIkBphHcYZ+LbX0gU+jEwI/fEmOT6pdMH2CmsK7
AqKdYmDe1DR/vq2COSVcJ6u0VevBguL+EoXyDNYOLWvMOrDGYuJP55TcpYs5dcu7cIc8LY/fD2fy
0pFCYCg6tzTb2ClrU9lJ3buvUnEKYcuuxzV6xQb89alRt35ImehBPd3IpoQLe5yPPk0aWO9s4LHx
WC13yFFV6UHNc5XxeNEKD4KPU3REheQkOH2qMbhFg7/gzNn5WKcEKhEW2b3/v1tA9jiWeGCY+4zC
mQNGQVBjBEaq4Kvlf43AB3qbuqsC5IYCOKKCOBtEwKhrnrvzQgMMfC3IgApGW0Y8abxcWHe4Xy6S
rfTbPk6Q8fTMyq54Li0BOMNGxUkOoV+Wxf8XjdDh2hB7XGObWbSpkpEL87eOnMXqvBexhSid2e27
/PDQfLA/1k6AIvfTpUgbpfesHkZkwqesDBHSeLtN52NprlYSfAO7WYVmVxv5my09sGJq+IqzQQh7
hHdyAaOVmdpklYE0yRJNQQhbSbaQb7zX+H8SwW6agPzwcDiTiicmToXbB03w6ojLSEU/R9GoNyi0
aHWZXR8wcIdsDzRR6l/FSYD7ZyWUtbJScNYnjZOf0T4Zfnnhoa/5pJLdfAKs5lAPnzNVXv8w1zj7
0rAhhd69fn306QTCnOn+i5JMyRX0TtG4ERhQxAVXU6X89oa9dPKG6P4Zqb9aAby6v+rqXV/tRaTl
g+0ilF8LupcLVBZGFGHAu9zq0bVxfLCeMdOI1fW595MGmoWD8jMzrY9Od/ElweIuniVILdntAruo
68HwJWIS4OTHh4yTjBDg1wdzWU5rtO3K0FAjmY7pZ6CfEJrwdq7jStDI2EH8RHgqaLlYW5dCo/Ex
sK/M7bBtp8YvT3BRFhaxleS0deTLR5MdngYgAZZIkmlOAMs+SdqjuBhRM3ScsD8lZCQ0jPtKJ32E
kP3G8/wD+gA9HBUMZcF0AP6+MIUx0qhyrTzgV68068CRk0TPOSGh7QhnLFctZDdAeUjB9YmkJoeh
JiAeuZGSmjXZVqxmncx0oZV7Yih5n1bIEArPi+aSIBCOSZWpsHO2tFB0YGkemBZiR/+8/taee40l
wGIC2wD4cRGc1jHTZqiI6IoFZnOGSiMvjut3hoER5870vaWtJ4y34yP3GEjRI8GCyuDLieDKUS0f
Tik+uacMc3LfA5ES3VHDtAow448c/IQhgZLVLa6q5ufU1kJcBeIWkRfcqj+SNTW1XOorfbD7rSNa
TVNvuH6ga70q3VNaeH8sQYiqCYmOX5534EcP8qfav6XHS1MgIzZ2jpjvS713HWmwGUBesUpwRRLQ
JHNg6LtxE4J+JPLFVoq1mCWTSOo4hqCOEjGr/YomeltN195bIWL3LYqvAeeINe/mWizwYkH426ng
fngV0unZWiqs7NEKl34kHgJ+e5lDND2Atg0trIPbnB9k+UsJswEsLe+yGdySFvM0i1iTJWkqYB80
qouL/dQEGNIxMvpD0ayth/JWHoRfH7dSn2qiO11j5LEhpBKCvbsU9DE0qR6bvRwY5obMtRN3UtSp
D4N/qlE/ee0q6Nkh+JD/IxX8gQyjThCp